 
import { Injectable } from '@nestjs/common';
import { DbService } from '../../../db/db.service';
import { ClinicContextService } from '../../../common/services/clinic-context.service';
import { AppLogger } from '../../../common/services/logger.service';
import { AuditLogService } from '../../../common/services/audit-log.service';
import { SettingsService } from '../../system/settings/settings.service';
import { Visit } from '@dental/shared';
import {
  SUMMARY_TEMPLATES,
  TREATMENT_KEYWORDS,
  DIAGNOSIS_KEYWORDS,
  RETURN_INTERVAL_DAYS,
  MAX_SUMMARY_LENGTH,
  TreatmentCategory,
} from './summary-templates';

export interface GenerateAndSaveResult {
  summary: string;
  nextReminder: string;
  wasAutoGenerated: boolean;
}

interface TreatmentMatch {
  templateId: keyof typeof SUMMARY_TEMPLATES;
  category: TreatmentCategory;
  tooth: string;
  replacements: Record<string, string>;
}

@Injectable()
export class MedicalSummaryService {
  private logger = new AppLogger(MedicalSummaryService.name);
  private auditLogService = new AuditLogService();

  constructor(
    private dbService: DbService,
    private clinicContext: ClinicContextService,
    private settingsService: SettingsService,
  ) {}

  async generateAndSave(visitId: string): Promise<GenerateAndSaveResult> {
    const enabled = await this.settingsService.getBoolean('aiMedicalSummaryEnabled', true);
    if (!enabled) {
      this.logger.log(`[SKIP] aiMedicalSummaryEnabled=false, 跳过自动摘要生成 visitId=${visitId}`);
      return { summary: '', nextReminder: '', wasAutoGenerated: false };
    }

    const { clause: clinicClause, params: clinicParams } = this.buildClinicClause();
    const clinicId = this.clinicContext.getClinicId() ?? null;

    const visit = this.dbService
      .prepare(`SELECT id, patientId, chiefComplaint, diagnosis, startTime, summaryAutoGenerated FROM Visit WHERE id = ? AND deletedAt IS NULL${clinicClause}`)
      .get(visitId, ...clinicParams) as (Visit & { summaryAutoGenerated?: number }) | undefined;

    if (!visit) {
      this.logger.warn(`[SKIP] Visit不存在 visitId=${visitId}`);
      return { summary: '', nextReminder: '', wasAutoGenerated: false };
    }

    if (visit.summaryAutoGenerated === 0) {
      this.logger.log(`[SKIP] summaryAutoGenerated=0，医生已手动修改，不覆盖 visitId=${visitId}`);
      return { summary: '', nextReminder: '', wasAutoGenerated: false };
    }

    const treatmentsRaw = this.dbService
      .prepare(`SELECT name, category, teethNumbers, status, completedDate FROM Treatment WHERE visitId = ? AND deletedAt IS NULL${clinicClause}`)
      .all(visitId, ...clinicParams) as Array<{ name?: string; category?: string; teethNumbers?: string; status?: string; completedDate?: string }>;
    const treatments = treatmentsRaw.map(t => ({
      name: t.name || '',
      category: (t.category || 'OTHER') as TreatmentCategory,
      teethNumbers: t.teethNumbers ? (JSON.parse(t.teethNumbers) as string[]) : [] as string[],
      completedDate: t.completedDate || null,
    }));

    const medicalRecordRaw = this.dbService
      .prepare(`SELECT chiefComplaint, diagnosis, treatmentPlan, teethInvolved FROM MedicalRecord WHERE visitId = ? AND deletedAt IS NULL LIMIT 1${clinicClause}`)
      .get(visitId, ...clinicParams) as { chiefComplaint?: string; diagnosis?: string; treatmentPlan?: string; teethInvolved?: string } | undefined;
    const medicalRecords = medicalRecordRaw ? {
      chiefComplaint: medicalRecordRaw.chiefComplaint || '',
      diagnosis: medicalRecordRaw.diagnosis || '',
      treatmentPlan: medicalRecordRaw.treatmentPlan || '',
      teethInvolved: medicalRecordRaw.teethInvolved ? (JSON.parse(medicalRecordRaw.teethInvolved) as string[]) : [] as string[],
    } : undefined;

    const { summary, nextReminder } = this.generateSummary({
      visit,
      treatments,
      medicalRecord: medicalRecords,
    });

    const now = new Date().toISOString();
    const result = this.dbService.prepare(
      `UPDATE Visit SET summary = ?, nextReminder = ?, summaryAutoGenerated = 1, updatedAt = ? WHERE id = ? AND (summaryAutoGenerated IS NULL OR summaryAutoGenerated != 0) AND deletedAt IS NULL${clinicClause}`,
    ).run(summary, nextReminder, now, visitId, ...clinicParams);

    if (result.changes === 0) {
      this.logger.log(`[SKIP] UPDATE 条件未命中（summaryAutoGenerated=0 已被并发写入）visitId=${visitId}`);
      return { summary, nextReminder, wasAutoGenerated: false };
    }

    this.auditLogService.logAudit(
      this.dbService,
      'MEDICAL_SUMMARY_AUTO_GENERATED',
      visitId,
      'Visit',
      clinicId,
      { afterData: { summary, nextReminder } },
    );

    this.logger.log(`[OK] 自动摘要生成 visitId=${visitId} nextReminder=${nextReminder}`);
    return { summary, nextReminder, wasAutoGenerated: true };
  }

  private buildClinicClause(): { clause: string; params: unknown[] } {
    const clinicId = this.clinicContext.getClinicId();
    if (!clinicId) return { clause: '', params: [] };
    return { clause: ' AND clinicId = ?', params: [clinicId] };
  }

  generateSummary(input: {
    visit: { chiefComplaint?: string; diagnosis?: string; startTime: string };
    treatments: Array<{ name: string; category?: string; teethNumbers?: string[] }>;
    medicalRecord?: { chiefComplaint?: string; diagnosis?: string; teethInvolved?: string[] };
  }): { summary: string; nextReminder: string } {
    const { visit, treatments, medicalRecord } = input;

    const matches: TreatmentMatch[] = [];
    const diagnosis = visit.diagnosis || medicalRecord?.diagnosis || '';
    const chiefComplaint = visit.chiefComplaint || medicalRecord?.chiefComplaint || '';

    for (const t of treatments) {
      const match = this.matchTreatment(t, diagnosis);
      if (match) matches.push(match);
    }

    if (matches.length === 0 && diagnosis) {
      const diagMatch = this.matchDiagnosis(diagnosis, chiefComplaint, medicalRecord?.teethInvolved);
      if (diagMatch) matches.push(diagMatch);
    }

    if (matches.length === 0) {
      if (chiefComplaint || diagnosis) {
        const teeth = medicalRecord?.teethInvolved?.join(',') || '患牙';
        matches.push({
          templateId: 'T9',
          category: 'CHECKUP',
          tooth: teeth,
          replacements: {
            issue: (chiefComplaint || diagnosis).slice(0, 30) || '口腔常规检查',
          },
        });
      } else {
        matches.push({
          templateId: 'T0',
          category: 'CHECKUP',
          tooth: '',
          replacements: {},
        });
      }
    }

    const uniqueMatches = this.dedupeByToothAndTemplate(matches);
    const summaryLines = uniqueMatches.map((m) => this.renderTemplate(m));

    let rawSummary: string;
    if (summaryLines.length <= 3) {
      rawSummary = summaryLines.join('；');
    } else {
      const firstThree = summaryLines.slice(0, 3).join('；');
      rawSummary = firstThree + '…';
    }

    let finalSummary = rawSummary;
    if (finalSummary.length > MAX_SUMMARY_LENGTH) {
      finalSummary = finalSummary.slice(0, MAX_SUMMARY_LENGTH - 1) + '…';
    }

    const minInterval = Math.min(...uniqueMatches.map((m) => RETURN_INTERVAL_DAYS[m.category] ?? RETURN_INTERVAL_DAYS.OTHER));
    const nextReminder = this.addDays(visit.startTime, minInterval);

    return { summary: finalSummary, nextReminder };
  }

  private matchTreatment(
    treatment: { name: string; category?: string; teethNumbers?: string[] },
    diagnosis: string,
  ): TreatmentMatch | null {
    const tooth = this.toothStr(treatment.teethNumbers);
    for (const rule of TREATMENT_KEYWORDS) {
      if (rule.keys.some((k) => treatment.name.includes(k))) {
        const replacements: Record<string, string> = {};
        if (rule.extractors) {
          if (rule.extractors.action) replacements.action = rule.extractors.action(treatment.name);
          if (rule.extractors.disease) replacements.disease = rule.extractors.disease(diagnosis);
          if (rule.extractors.depth) replacements.depth = rule.extractors.depth(treatment.name, diagnosis);
          if (rule.extractors.material) replacements.material = rule.extractors.material(treatment.name);
          if (rule.extractors.phase) replacements.phase = rule.extractors.phase(treatment.name);
          if (rule.extractors.adjustment) replacements.adjustment = rule.extractors.adjustment(treatment.name);
          if (rule.extractors.surgery) replacements.surgery = rule.extractors.surgery(treatment.name);
        }
        return {
          templateId: rule.templateId,
          category: rule.category,
          tooth,
          replacements,
        };
      }
    }
    return null;
  }

  private matchDiagnosis(
    diagnosis: string,
    chiefComplaint: string,
    teethInvolved?: string[],
  ): TreatmentMatch | null {
    const tooth = this.toothStr(teethInvolved);
    for (const rule of DIAGNOSIS_KEYWORDS) {
      if (rule.keys.some((k) => diagnosis.includes(k))) {
        const replacements: Record<string, string> = {};
        if (rule.category === 'ROOT_CANAL') {
          replacements.disease = diagnosis.split(/[，,、]/)[0] || '牙髓炎';
          replacements.action = '';
        }
        if (rule.category === 'FILLING') {
          if (diagnosis.includes('深')) replacements.depth = '深';
          else if (diagnosis.includes('中')) replacements.depth = '中';
          else if (diagnosis.includes('浅')) replacements.depth = '浅';
          else replacements.depth = '中';
        }
        return {
          templateId: rule.templateId,
          category: rule.category,
          tooth,
          replacements,
        };
      }
    }
    return null;
  }

  private dedupeByToothAndTemplate(matches: TreatmentMatch[]): TreatmentMatch[] {
    const seen = new Map<string, TreatmentMatch>();
    for (const m of matches) {
      const key = `${m.templateId}|${m.tooth}`;
      if (!seen.has(key)) {
        seen.set(key, m);
      }
    }
    return Array.from(seen.values());
  }

  private renderTemplate(match: TreatmentMatch): string {
    let template = SUMMARY_TEMPLATES[match.templateId];
    const tooth = match.tooth || '患牙';
    // eslint-disable-next-line unicorn/no-unsafe-string-replacement -- 模板变量来自内部枚举，非用户输入
    template = template.replace(/\{tooth\}/g, tooth);
    for (const [k, v] of Object.entries(match.replacements)) {
      const pattern = new RegExp(`\\{${k}\\}`, 'g');
      // eslint-disable-next-line unicorn/no-unsafe-string-replacement -- 模板变量来自内部枚举，非用户输入
      template = template.replace(pattern, v || '');
    }
    return template;
  }

  private toothStr(teethNumbers?: string[]): string {
    if (!teethNumbers || teethNumbers.length === 0) return '';
    return teethNumbers.join(',');
  }

  private addDays(isoDateStr: string, days: number): string {
    const d = new Date(isoDateStr);
    if (isNaN(d.getTime())) {
      const fallback = new Date();
      fallback.setDate(fallback.getDate() + days);
      return fallback.toISOString().slice(0, 10);
    }
    d.setDate(d.getDate() + days);
    return d.toISOString().slice(0, 10);
  }
}
