import { IsOptional, IsString, MaxLength, IsInt, Min, Max } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CompleteVisitDto {
  @ApiProperty({ description: '诊断结果', example: '16深龋，26中龋', required: false })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  diagnosis?: string;

  @ApiProperty({ description: '治疗计划', example: '16树脂充填，26建议观察', required: false })
  @IsOptional()
  @IsString()
  @MaxLength(3000)
  treatmentPlan?: string;

  @ApiProperty({ description: '下次就诊提醒日期（YYYY-MM-DD），医生手动传入则优先', example: '2026-08-14', required: false })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  nextReminder?: string;

  @ApiProperty({ description: '是否为医生手动填写（0=手动，1=自动生成后可覆盖），医生手动传 0 表示不允许后续自动覆盖', example: 0, required: false })
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(1)
  summaryAutoGenerated?: number;
}
