/**
 * 审计日志类型常量
 *
 * 统一管理所有写入 AuditLog.type 字段的字符串值，避免在各 Service 中硬编码。
 * 枚举值必须与历史已落库的字符串完全一致（仅大小写敏感的 UPPER_SNAKE_CASE），
 * 否则将导致按 type 检索审计日志时遗漏历史数据。
 *
 * 采用 `const` 对象 + `as const` 模式，与 @dental/shared 的枚举风格保持一致，
 * 既保留运行时值，又能推导出字面量联合类型。
 */
export const AuditLogType = {
  // 认证与用户
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  // eslint-disable-next-line sonarjs/no-hardcoded-passwords
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',

  // 通用数据操作（BaseService）
  SOFT_DELETE: 'SOFT_DELETE',
  HARD_DELETE: 'HARD_DELETE',

  // 患者敏感数据访问
  PHONE_ACCESS: 'PHONE_ACCESS',
  ID_CARD_ACCESS: 'ID_CARD_ACCESS',

  // 系统设置
  SETTING_UPDATE: 'SETTING_UPDATE',
  SETTING_DELETE: 'SETTING_DELETE',

  // 备份
  BACKUP_RESTORE: 'BACKUP_RESTORE',

  // 排班
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  APPOINTMENT_REMOVE: 'APPOINTMENT_REMOVE',

  // 就诊与挂号
  REGISTRATION_CREATE: 'REGISTRATION_CREATE',
  REGISTRATION_START_VISIT: 'REGISTRATION_START_VISIT',
  REGISTRATION_CANCEL: 'REGISTRATION_CANCEL',
  VISIT_CREATE: 'VISIT_CREATE',
  VISIT_COMPLETE: 'VISIT_COMPLETE',

  // 病历
  MEDICAL_RECORD_UPDATE: 'MEDICAL_RECORD_UPDATE',
  MEDICAL_RECORD_LOCK: 'MEDICAL_RECORD_LOCK',
  MODIFY_REQUEST_REVIEW: 'MODIFY_REQUEST_REVIEW',

  // 初诊
  FIRST_EXAM_STATUS_UPDATE: 'FIRST_EXAM_STATUS_UPDATE',
  FIRST_EXAM_RESTART: 'FIRST_EXAM_RESTART',

  // 治疗与治疗计划
  TREATMENT_CREATE: 'TREATMENT_CREATE',
  TREATMENT_UPDATE: 'TREATMENT_UPDATE',
  TREATMENT_PLAN_ITEM_STATUS_UPDATE: 'TREATMENT_PLAN_ITEM_STATUS_UPDATE',
  TREATMENT_CATALOG_CREATE: 'TREATMENT_CATALOG_CREATE',
  TREATMENT_CATALOG_UPDATE: 'TREATMENT_CATALOG_UPDATE',
  TREATMENT_CATALOG_DELETE: 'TREATMENT_CATALOG_DELETE',

  // 牙位记录
  TOOTH_RECORD_CREATE: 'TOOTH_RECORD_CREATE',
  TOOTH_RECORD_UPDATE: 'TOOTH_RECORD_UPDATE',
  TOOTH_RECORD_REMOVE: 'TOOTH_RECORD_REMOVE',

  // 处方
  PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',

  // 随访
  FOLLOWUP_UPDATE: 'FOLLOWUP_UPDATE',
  FOLLOWUP_COMPLETE: 'FOLLOWUP_COMPLETE',
  FOLLOWUP_REMOVE: 'FOLLOWUP_REMOVE',

  // 收费与欠费
  CHARGE_CREATE: 'CHARGE_CREATE',
  CHARGE_PAY: 'CHARGE_PAY',
  DEBT_CREATE: 'DEBT_CREATE',
  DEBT_PAY: 'DEBT_PAY',
  REFUND: 'REFUND',

  // 收费套餐
  COMBO_UPDATE: 'COMBO_UPDATE',
  COMBO_DELETE: 'COMBO_DELETE',

  // 会员卡
  MEMBER_CARD_RECHARGE: 'MEMBER_CARD_RECHARGE',
  MEMBER_CARD_CONSUME: 'MEMBER_CARD_CONSUME',
  MEMBER_CARD_REFUND: 'MEMBER_CARD_REFUND',

  // 库存
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
  STOCK_IN: 'STOCK_IN',
  STOCK_OUT: 'STOCK_OUT',
  STOCK_ADJUST: 'STOCK_ADJUST',

  // 采购与加工
  PURCHASE_ORDER_CREATE: 'PURCHASE_ORDER_CREATE',
  PURCHASE_ORDER_RECEIVE: 'PURCHASE_ORDER_RECEIVE',
  PURCHASE_ORDER_CANCEL: 'PURCHASE_ORDER_CANCEL',
  PROCESSING_ORDER_STATUS_UPDATE: 'PROCESSING_ORDER_STATUS_UPDATE',
  PROCESSING_ORDER_UPDATE: 'PROCESSING_ORDER_UPDATE',
  PROCESSING_ORDER_REMOVE: 'PROCESSING_ORDER_REMOVE',
  PROCESSING_ORDER_LINK_CHARGE: 'PROCESSING_ORDER_LINK_CHARGE',
  PROCESSING_FLOW_LOG: 'PROCESSING_FLOW_LOG',
  PROCESSING_PRODUCT_CREATE: 'PROCESSING_PRODUCT_CREATE',
  PROCESSING_PRODUCT_UPDATE: 'PROCESSING_PRODUCT_UPDATE',
  PROCESSING_PRODUCT_DELETE: 'PROCESSING_PRODUCT_DELETE',
  PROCESSING_FACTORY_CREATE: 'PROCESSING_FACTORY_CREATE',
  PROCESSING_FACTORY_UPDATE: 'PROCESSING_FACTORY_UPDATE',
  PROCESSING_FACTORY_DELETE: 'PROCESSING_FACTORY_DELETE',

  // 设备
  EQUIPMENT_CREATE: 'EQUIPMENT_CREATE',
  EQUIPMENT_UPDATE: 'EQUIPMENT_UPDATE',
  EQUIPMENT_DELETE: 'EQUIPMENT_DELETE',

  // 影像
  IMAGING_CREATE: 'IMAGING_CREATE',
  IMAGING_UPDATE: 'IMAGING_UPDATE',
  IMAGING_DELETE: 'IMAGING_DELETE',

  // 口腔检查
  ORAL_EXAM_CREATE: 'ORAL_EXAM_CREATE',
  ORAL_EXAM_UPDATE: 'ORAL_EXAM_UPDATE',
  ORAL_EXAM_DELETE: 'ORAL_EXAM_DELETE',

  // 牙周记录
  PERIODONTAL_RECORD_CREATE: 'PERIODONTAL_RECORD_CREATE',
  PERIODONTAL_RECORD_UPDATE: 'PERIODONTAL_RECORD_UPDATE',
  PERIODONTAL_RECORD_DELETE: 'PERIODONTAL_RECORD_DELETE',

  // 支付方式
  PAYMENT_METHOD_CREATE: 'PAYMENT_METHOD_CREATE',
  PAYMENT_METHOD_UPDATE: 'PAYMENT_METHOD_UPDATE',
  PAYMENT_METHOD_TOGGLE: 'PAYMENT_METHOD_TOGGLE',

  // 牙椅
  CHAIR_CREATE: 'CHAIR_CREATE',
  CHAIR_UPDATE: 'CHAIR_UPDATE',
  CHAIR_DELETE: 'CHAIR_DELETE',

  // 药品库存
  DRUG_STOCK_DEDUCT: 'DRUG_STOCK_DEDUCT',

  // 病历字典
  MEDICAL_RECORD_PHRASE_CREATE: 'MEDICAL_RECORD_PHRASE_CREATE',
  MEDICAL_RECORD_PHRASE_UPDATE: 'MEDICAL_RECORD_PHRASE_UPDATE',
  MEDICAL_RECORD_PHRASE_DELETE: 'MEDICAL_RECORD_PHRASE_DELETE',
  MEDICAL_RECORD_TEMPLATE_CREATE: 'MEDICAL_RECORD_TEMPLATE_CREATE',
  MEDICAL_RECORD_TEMPLATE_UPDATE: 'MEDICAL_RECORD_TEMPLATE_UPDATE',
  MEDICAL_RECORD_TEMPLATE_DELETE: 'MEDICAL_RECORD_TEMPLATE_DELETE',
  MODIFY_REQUEST_CREATE: 'MODIFY_REQUEST_CREATE',

  // 挂号
  REGISTRATION_UPDATE: 'REGISTRATION_UPDATE',

  // 诊所
  CLINIC_CREATE: 'CLINIC_CREATE',

  // 初诊
  FIRST_EXAM_FOLLOWUP_CREATE: 'FIRST_EXAM_FOLLOWUP_CREATE',
  FIRST_EXAM_TOOTH_UPDATE: 'FIRST_EXAM_TOOTH_UPDATE',
  FIRST_EXAM_TRACK_UPDATE: 'FIRST_EXAM_TRACK_UPDATE',
} as const;

// eslint-disable-next-line no-redeclare
export type AuditLogType = typeof AuditLogType[keyof typeof AuditLogType];
