/**
 * 数据库表名常量
 * 统一管理所有表名，避免硬编码
 */
export const TableNames = {
  USER: 'User',
  PATIENT: 'Patient',
  APPOINTMENT: 'Appointment',
  VISIT: 'Visit',
  TREATMENT: 'Treatment',
  TREATMENT_PLAN: 'TreatmentPlan',
  TREATMENT_PLAN_ITEM: 'TreatmentPlanItem',
  PRESCRIPTION: 'Prescription',
  PRESCRIPTION_ITEM: 'PrescriptionItem',
  MEDICAL_RECORD: 'MedicalRecord',
  MEDICAL_RECORD_PHRASE: 'MedicalRecordPhrase',
  MEDICAL_RECORD_TEMPLATE: 'MedicalRecordTemplate',
  RECORD_MODIFY_REQUEST: 'RecordModifyRequest',
  REGISTRATION: 'Registration',
  FIRST_EXAM: 'FirstExam',
  FIRST_EXAM_TRACK: 'FirstExamTrack',
  FIRST_EXAM_TOOTH: 'FirstExamTooth',
  FIRST_EXAM_FOLLOW_UP: 'FirstExamFollowUp',
  ORAL_EXAMINATION: 'OralExamination',
  PERIODONTAL_RECORD: 'PeriodontalRecord',
  CHARGE: 'Charge',
  CHARGE_ITEM: 'ChargeItem',
  CHARGE_COMBO: 'ChargeCombo',
  PAYMENT_METHOD: 'PaymentMethod',
  DEBT_RECORD: 'DebtRecord',
  REFUND: 'Refund',
  INVENTORY_ITEM: 'InventoryItem',
  INVENTORY_TRANSACTION: 'InventoryTransaction',
  SUPPLIER: 'Supplier',
  EQUIPMENT: 'Equipment',
  CHAIR: 'Chair',
  IMAGING: 'Imaging',
  FOLLOW_UP: 'FollowUp',
  DRUG_CATALOG: 'DrugCatalog',
  TREATMENT_CATALOG: 'TreatmentCatalog',
  OPERATION_LOG: 'OperationLog',
  BACKUP_RECORD: 'BackupRecord',
  IDEMPOTENCY_RECORD: 'IdempotencyRecord',
  WECHAT_MESSAGE: 'WechatMessage',
  CLINIC_INFO: 'ClinicInfo',
} as const;

export type TableName = typeof TableNames[keyof typeof TableNames];
