// UI 枚举/隐藏/只读/提示字典（M-04：由 ui-meta-data.ts 拆分）

export const commonEnumLabels: Record<string, string> = {
  MALE: '男',
  FEMALE: '女',
  UNKNOWN: '未知',
  WALK_IN: '到店',
  REFERRAL: '转介绍',
  ONLINE: '线上',
  OTHER: '其他',
  PENDING: '待处理',
  IN_PROGRESS: '进行中',
  COMPLETED: '已完成',
  CANCELLED: '已取消',
  ACTIVE: '启用',
  INACTIVE: '停用',
  DISABLED: '禁用',
  FROZEN: '冻结',
  EXPIRED: '过期',
  NORMAL: '普通',
  VIP: 'VIP',
  SVIP: 'SVIP',
  BOOKED: '已预约',
  ARRIVED: '已到诊',
  IN_CHAIR: '就诊中',
  NO_SHOW: '未到诊',
  REGULAR: '常规',
  FOLLOW_UP: '随访',
  EMERGENCY: '急诊',
  CONSULTATION: '咨询',
  UNPAID: '未付款',
  PARTIAL: '部分付款',
  PAID: '已付款',
  REFUNDED: '已退款',
  RECEIVED: '已收货',
  BOSS: '老板',
  ADMIN: '管理员',
  DOCTOR: '医生',
  RECEPTIONIST: '前台',
  NURSE: '护士',
  TECHNICIAN: '技师',
  REVENUE_DROP: '收入下降',
  NEW_PATIENTS: '新患者',
  NO_SHOW_RATE: '失约率',
  AOV: '客单价',
  INVENTORY_STOCKOUT: '库存缺货',
  SCHEDULER_TASK_FAILURE: '定时任务失败',
  PERFORMANCE_ANOMALY: '绩效异常',
  SATISFACTION_NEGATIVE: '差评',
  INFO: '信息',
  WARNING: '警告',
  CRITICAL: '严重',
  WARN: '警告',
  APPLIED: '已应用',
  IGNORED: '已忽略',
  CASH: '现金',
  WECHAT: '微信',
  ALIPAY: '支付宝',
  CARD: '银行卡',
  DEBT: '欠费',
  MEMBER_CARD: '会员卡',
  UNIONPAY: '银联',
  INSURANCE: '医保',
  OPEN: '待处理',
  ACKNOWLEDGED: '已确认',
  RESOLVED: '已解决',
  APPROVED: '已批准',
  REJECTED: '已拒绝',
  LOW: '低',
  MEDIUM: '中',
  HIGH: '高',
  EXTREME: '极高',
  IN: '入库',
  OUT: '出库',
  ADJUST: '调整',
  MAINTENANCE: '维护中',
  BROKEN: '故障',
  SCRAPPED: '报废',
  DRAFT: '草稿',
  SENT: '已发送',
  REGISTERED: '已挂号',
  TRIAGED: '已分诊',
  PLANNED: '已计划',
  SUCCESS: '成功',
  FAILED: '失败',
  VERIFYING: '校验中',
  INSERT: '新增',
  UPDATE: '更新',
  DELETE: '删除',
};

export const hiddenFields = new Set([
  'id',
  'clinicId',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'passwordHash',
  'refreshToken',
  'tokenHash',
  'role',
  'loginAttempts',
  'lockedUntil',
  'tokenVersion',
  'currentClinicId',
  'paidAmount',
  'refundedAmount',
  'balance',
  'totalRecharge',
  'totalConsume',
  'points',
  'totalPoints',
  'stock',
  'minStock',
]);

export const readOnlyFields = new Set([
  'id',
  'clinicId',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'passwordHash',
  'refreshToken',
  'tokenHash',
  'role',
  'loginAttempts',
  'lockedUntil',
  'tokenVersion',
  'currentClinicId',
  'number',
  'totalAmount',
  'paidAmount',
  'refundedAmount',
  'balance',
  'totalRecharge',
  'totalConsume',
  'points',
  'totalPoints',
  'stock',
  'minStock',
  'beforeStock',
  'afterStock',
]);

export const helpTexts: Record<string, string> = {
  password: '至少 8 位',
  phone: '用于预约和随访联系',
  idCard: '用于建档和身份核对',
  birthDate: '格式：YYYY-MM-DD',
};
