import type { ResourceDefinition, ResourceField } from '../../domain/contracts';

const resourceLabels: Record<string, string> = {
  clinics: '诊所',
  users: '员工',
  patients: '患者档案',
  familyMembers: '家属联系人',
  patientRiskScores: '风险评估',
  chairs: '椅位',
  appointments: '预约',
  registrations: '挂号',
  visits: '就诊',
  firstExams: '首诊',
  firstExamTeeth: '首诊牙位',
  oralExaminations: '口腔检查',
  periodontalRecords: '牙周记录',
  medicalRecords: '病历',
  medicalPhrases: '医学短语',
  toothRecords: '牙位记录',
  imaging: '影像',
  treatmentCatalogs: '治疗项目',
  treatments: '治疗',
  treatmentPlans: '治疗计划',
  treatmentPlanItems: '治疗计划明细',
  charges: '收费单',
  chargeItems: '收费明细',
  debtRecords: '欠费',
  memberCards: '会员卡',
  memberCardLogs: '会员卡流水',
  memberPointLogs: '会员积分流水',
  refunds: '退款',
  drugCatalogItems: '药品目录',
  prescriptions: '处方',
  prescriptionItems: '处方明细',
  suppliers: '供应商',
  inventoryItems: '库存项目',
  inventoryTransactions: '库存流水',
  purchaseOrders: '采购单',
  purchaseOrderItems: '采购明细',
  processingFactories: '加工厂',
  processingOrders: '加工单',
  processingOrderItems: '加工明细',
  cephalometricCases: '头影测量',
  invoices: '发票',
  followUps: '随访',
  followUpTemplates: '随访模板',
  wechatMessages: '微信消息',
  satisfactionSurveys: '满意度',
  equipment: '设备',
  workSchedules: '排班',
  attendance: '考勤',
  leaveRequests: '请假',
  notifications: '通知',
  settings: '设置',
  businessAlerts: '业务告警',
  operationLogs: '操作日志',
  syncChanges: '同步记录',
  printTemplates: '打印模板',
  dataImportJobs: '导入任务',
  inventoryReplenishmentSuggestions: '补货建议',
};

const fieldLabels: Record<string, string> = {
  id: 'ID',
  clinicId: '诊所',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  deletedAt: '删除时间',
  code: '编号',
  name: '名称',
  notes: '备注',
  username: '用户名',
  password: '密码',
  passwordHash: '密码',
  phone: '电话',
  gender: '性别',
  birthDate: '出生日期',
  idCard: '身份证号',
  address: '地址',
  occupation: '职业',
  remark: '备注',
  avatar: '头像',
  tags: '标签',
  allergies: '过敏史',
  medicalHistory: '既往病史',
  medicationHistory: '用药史',
  systemicDiseases: '全身疾病',
  source: '来源',
  active: '启用',
  role: '角色',
  patientId: '患者',
  doctorId: '医生',
  chairId: '椅位',
  relationId: '关联 ID',
  registeredAt: '登记时间',
  visitId: '就诊',
  appointmentId: '预约',
  planId: '治疗计划',
  startTime: '开始时间',
  endTime: '结束时间',
  status: '状态',
  type: '类型',
  title: '标题',
  content: '内容',
  data: '数据',
  description: '说明',
  result: '结果',
  reason: '原因',
  amount: '金额',
  totalAmount: '应收金额',
  paidAmount: '实收金额',
  refundedAmount: '退款金额',
  discount: '优惠金额',
  payMethod: '支付方式',
  paidAt: '收款时间',
  cardId: '会员卡',
  cardNo: '卡号',
  balance: '余额',
  totalRecharge: '累计充值',
  totalConsume: '累计消费',
  points: '积分',
  totalPoints: '累计积分',
  level: '会员等级',
  memberCardId: '会员卡',
  chargeId: '收费单',
  operatorId: '操作员',
  operatorName: '操作员',
  price: '单价',
  unitPrice: '单价',
  quantity: '数量',
  subtotal: '小计',
  teethNumbers: '牙位',
  itemId: '物品',
  inventoryId: '库存项目',
  supplierId: '供应商',
  stock: '库存',
  minStock: '最低库存',
  unit: '单位',
  spec: '规格',
  category: '分类',
  expireDate: '有效期至',
  location: '位置',
  orderId: '订单',
  factoryId: '加工厂',
  number: '单号',
  shade: '颜色',
  totalFee: '费用',
  sentAt: '发送时间',
  expectedAt: '预计日期',
  receivedAt: '收货时间',
  deliveredAt: '送达时间',
  planDate: '计划日期',
  assigneeId: '负责人',
  templateId: '模板',
  filename: '文件名',
  fileSize: '文件大小',
  encrypted: '已加密',
  workDate: '工作日期',
  checkIn: '签到时间',
  checkOut: '签退时间',
  startDate: '开始日期',
  endDate: '结束日期',
  reviewerId: '审批人',
  reviewedAt: '审批时间',
  userName: '用户名',
  action: '操作',
  target: '对象',
  detail: '详情',
  ip: 'IP 地址',
  traceId: '追踪 ID',
  tableName: '表名',
  recordId: '记录 ID',
  operation: '操作',
  deviceId: '设备 ID',
  imageUrl: '图片地址',
  thumbnailUrl: '缩略图',
  takenAt: '拍摄时间',
  diagnosis: '诊断',
  chiefComplaint: '主诉',
  treatmentPlan: '治疗计划',
  treatmentSuggestion: '治疗建议',
  oralExam: '口腔检查',
  auxiliaryExam: '辅助检查',
  presentIllness: '现病史',
  pastHistory: '既往史',
  allergyHistory: '过敏史',
  examination: '检查',
  teethInvolved: '涉及牙位',
  isLocked: '已锁定',
  lockedAt: '锁定时间',
  lockedBy: '锁定人',
  signature: '签名',
  importType: '导入类型',
  fileName: '文件名',
  totalRows: '总行数',
  successRows: '成功行数',
  failedRows: '失败行数',
  errorReportPath: '错误报告',
  startedById: '操作人',
  completedAt: '完成时间',
  createdBy: '创建人',
  loginAttempts: '登录失败次数',
  lockedUntil: '锁定至',
  tokenVersion: '令牌版本',
  relationship: '关系',
  cariesScore: '龋齿评分',
  periodontalScore: '牙周评分',
  implantScore: '种植评分',
  cariesLevel: '龋齿风险等级',
  periodontalLevel: '牙周风险等级',
  implantLevel: '种植风险等级',
  factorSnapshotJson: '风险因子快照',
  assessedById: '评估人',
  triageNote: '分诊备注',
  registeredBy: '挂号人',
  triagedAt: '分诊时间',
  startedAt: '开始时间',
  summary: '就诊小结',
  nextReminder: '下次提醒',
  consultantId: '咨询医生',
  examId: '首诊',
  toothNumber: '牙位号',
  toothStatus: '牙位状态',
  diseases: '疾病',
  isChief: '主诉牙位',
  examDate: '检查日期',
  plaqueIndex: '菌斑指数',
  boneLoss: '骨吸收',
  isTemplate: '是否模板',
  images: '图片',
  sortOrder: '排序',
  currentStatus: '当前状态',
  conditions: '牙位情况',
  plannedDate: '计划日期',
  completedDate: '完成日期',
  treatmentId: '治疗',
  balanceAfter: '操作后余额',
  referenceId: '关联记录',
  pointsAfter: '操作后积分',
  specification: '规格',
  prescriptionId: '处方',
  drugId: '药品',
  dosage: '剂量',
  frequency: '频次',
  days: '天数',
  contactPerson: '联系人',
  bankAccount: '银行账号',
  beforeStock: '操作前库存',
  afterStock: '操作后库存',
  referenceType: '关联类型',
  landmarksJson: '标记点',
  metricsJson: '测量结果',
  issuedAt: '开具时间',
  daysAfter: '间隔天数',
  isEnabled: '启用',
  triggerTreatmentCodes: '触发治疗编码',
  triggerTreatmentCategories: '触发治疗分类',
  minIntervalDays: '最小间隔天数',
  recommendedIntervalDays: '推荐间隔天数',
  maxIntervalDays: '最大间隔天数',
  riskMultiplierLow: '低风险系数',
  riskMultiplierMedium: '中风险系数',
  riskMultiplierHigh: '高风险系数',
  riskMultiplierExtreme: '极高风险系数',
  requiresAdherenceCheck: '需检查依从性',
  score: '评分',
  channel: '渠道',
  comment: '评价',
  surveyDate: '问卷日期',
  model: '型号',
  brand: '品牌',
  serialNumber: '序列号',
  purchasePrice: '采购价',
  purchaseDate: '采购日期',
  supplier: '供应商',
  remarks: '备注',
  userId: '员工',
  body: '正文',
  kind: '类型',
  readAt: '阅读时间',
  key: '键',
  value: '值',
  alertType: '告警类型',
  severity: '严重程度',
  metricName: '指标',
  currentValue: '当前值',
  baselineValue: '基线值',
  deviationPercent: '偏差百分比',
  message: '消息',
  suggestion: '建议',
  occurredAt: '发生时间',
  acknowledged: '已确认',
  acknowledgedBy: '确认人',
  acknowledgedAt: '确认时间',
  variables: '变量',
  isDefault: '默认模板',
  paperSize: '纸张',
  orientation: '方向',
  avgDailyConsumption: '日均消耗',
  leadTimeDays: '采购周期',
  safetyFactor: '安全系数',
  rop: '补货点',
  suggestedQty: '建议数量',
  calculationSnapshotJson: '计算快照',
};

const commonEnumLabels: Record<string, string> = {
  MALE: '男',
  FEMALE: '女',
  UNKNOWN: '未知',
  WALK_IN: '到店',
  REFERRAL: '转介绍',
  ONLINE: '线上',
  OTHER: '其他',
  PENDING: '待处理',
  IN_PROGRESS: '进行中',
  COMPLETED: '已完成',
  CANCELLED: '已取消',
  ACTIVE: '启用',
  INACTIVE: '停用',
  DISABLED: '禁用',
  FROZEN: '冻结',
  EXPIRED: '过期',
  NORMAL: '普通',
  VIP: 'VIP',
  SVIP: 'SVIP',
  BOOKED: '已预约',
  ARRIVED: '已到诊',
  IN_CHAIR: '就诊中',
  NO_SHOW: '未到诊',
  REGULAR: '常规',
  FOLLOW_UP: '随访',
  EMERGENCY: '急诊',
  CONSULTATION: '咨询',
  UNPAID: '未付款',
  PARTIAL: '部分付款',
  PAID: '已付款',
  REFUNDED: '已退款',
  RECEIVED: '已收货',
  BOSS: '老板',
  ADMIN: '管理员',
  DOCTOR: '医生',
  RECEPTIONIST: '前台',
  NURSE: '护士',
  TECHNICIAN: '技师',
  REVENUE_DROP: '收入下降',
  NEW_PATIENTS: '新患者',
  NO_SHOW_RATE: '失约率',
  AOV: '客单价',
  INVENTORY_STOCKOUT: '库存缺货',
  SCHEDULER_TASK_FAILURE: '定时任务失败',
  PERFORMANCE_ANOMALY: '绩效异常',
  SATISFACTION_NEGATIVE: '差评',
  INFO: '信息',
  WARNING: '警告',
  CRITICAL: '严重',
  WARN: '警告',
  APPLIED: '已应用',
  IGNORED: '已忽略',
  CASH: '现金',
  WECHAT: '微信',
  ALIPAY: '支付宝',
  CARD: '银行卡',
  DEBT: '欠费',
  MEMBER_CARD: '会员卡',
  UNIONPAY: '银联',
  INSURANCE: '医保',
  OPEN: '待处理',
  ACKNOWLEDGED: '已确认',
  RESOLVED: '已解决',
  APPROVED: '已批准',
  REJECTED: '已拒绝',
  LOW: '低',
  MEDIUM: '中',
  HIGH: '高',
  EXTREME: '极高',
  IN: '入库',
  OUT: '出库',
  ADJUST: '调整',
  MAINTENANCE: '维护中',
  BROKEN: '故障',
  SCRAPPED: '报废',
  DRAFT: '草稿',
  SENT: '已发送',
  REGISTERED: '已挂号',
  TRIAGED: '已分诊',
  PLANNED: '已计划',
  SUCCESS: '成功',
  FAILED: '失败',
  VERIFYING: '校验中',
  INSERT: '新增',
  UPDATE: '更新',
  DELETE: '删除',
};

const hiddenFields = new Set([
  'id',
  'clinicId',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'passwordHash',
  'refreshToken',
  'tokenHash',
  'role',
  'loginAttempts',
  'lockedUntil',
  'tokenVersion',
  'currentClinicId',
  'paidAmount',
  'refundedAmount',
  'balance',
  'totalRecharge',
  'totalConsume',
  'points',
  'totalPoints',
  'stock',
  'minStock',
]);

const readOnlyFields = new Set([
  'id',
  'clinicId',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'passwordHash',
  'refreshToken',
  'tokenHash',
  'role',
  'loginAttempts',
  'lockedUntil',
  'tokenVersion',
  'currentClinicId',
  'number',
  'totalAmount',
  'paidAmount',
  'refundedAmount',
  'balance',
  'totalRecharge',
  'totalConsume',
  'points',
  'totalPoints',
  'stock',
  'minStock',
  'beforeStock',
  'afterStock',
]);

const helpTexts: Record<string, string> = {
  password: '至少 8 位',
  phone: '用于预约和随访联系',
  idCard: '用于建档和身份核对',
  birthDate: '格式：YYYY-MM-DD',
};

function humanize(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/^./, (first) => first.toUpperCase());
}

function formatFor(type: ResourceField['type']): NonNullable<ResourceField['format']> {
  if (type === 'money') return 'money';
  if (type === 'date') return 'date';
  if (type === 'datetime') return 'datetime';
  if (type === 'json') return 'json';
  return 'text';
}

function inputTypeFor(type: ResourceField['type']): NonNullable<ResourceField['inputType']> {
  if (type === 'boolean') return 'checkbox';
  if (type === 'enum') return 'select';
  if (type === 'date') return 'date';
  if (type === 'datetime') return 'datetime';
  if (type === 'number' || type === 'money') return 'number';
  if (type === 'longText' || type === 'json') return 'textarea';
  return 'text';
}

export function applyUiMeta(definition: ResourceDefinition): ResourceDefinition {
  const resourceLabel = definition.label ?? resourceLabels[definition.name] ?? humanize(definition.name);
  const fields = definition.fields.map((field) => {
    const label = field.label ?? fieldLabels[field.name] ?? humanize(field.name);
    return {
      ...field,
      label,
      enumLabels: field.enumLabels ?? (field.type === 'enum' ? commonEnumLabels : undefined),
      format: field.format ?? formatFor(field.type),
      inputType: field.inputType ?? inputTypeFor(field.type),
      hidden: field.hidden ?? hiddenFields.has(field.name),
      readOnly: field.readOnly ?? readOnlyFields.has(field.name),
      placeholder: field.placeholder ?? label,
      helpText: field.helpText ?? helpTexts[field.name],
    };
  });
  return { ...definition, label: resourceLabel, fields };
}
