
// 枚举类型从 ./enums 复用，避免与 enums.ts 重复导出同名类型
import type {
  AppointmentType,
  AppointmentStatus,
  VisitStatus,
  TreatmentStatus,
  ChargeStatus,
  Gender,
  PatientSource,
  FollowUpStatus,
  RegistrationStatus,
  RegistrationType,
  PayMethod,
} from '../enums';

// DB row type for better-sqlite3 compatibility
export type DbRow = Record<string, unknown>;

export interface BaseEntity {
  id: string;
  clinicId?: string;
  createdAt: string;
  updatedAt?: string
}

export interface Pagination<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

export type UserRole = 'BOSS' | 'DOCTOR' | 'RECEPTIONIST' | 'NURSE' | 'ADMIN' | 'TECHNICIAN';

export interface User extends BaseEntity {
  username: string;
  passwordHash?: string;
  name: string;
  role: UserRole;
  phone?: string
  active: number;
  loginAttempts?: number;
  lockedUntil?: string
  tokenVersion?: number;
  refreshToken?: string
  refreshTokenExpiresAt?: string
}

export interface FamilyMember {
  id: string;
  name: string;
  code: string;
  phone: string;
  gender: string;
}

export interface Patient extends BaseEntity {
  code: string;
  name: string;
  gender: Gender;
  phone: string;
  birthDate?: string;
  idCard?: string;
  address?: string;
  occupation?: string;
  remark?: string;
  avatar?: string;
  tags: string[];
  allergies: string[];
  medicalHistory: string[];
  medicationHistory: string[];
  systemicDiseases: string[];
  source: PatientSource;
  familyId?: string;
  referrer?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  active: number;
  familyMembers?: FamilyMember[];
  deletedAt?: string;
}

export interface Appointment extends BaseEntity {
  patientId: string;
  doctorId: string;
  chairId?: string
  startTime: string;
  endTime: string;
  status: AppointmentStatus;
  type: AppointmentType;
  remark?: string
  visitId?: string
  deletedAt?: string
}

export interface Visit extends BaseEntity {
  patientId: string;
  appointmentId?: string
  doctorId: string;
  chiefComplaint?: string
  diagnosis?: string
  treatmentPlan?: string
  summary?: string | null;
  startTime: string;
  endTime?: string
  status: VisitStatus;
  nextReminder?: string | null;
  summaryAutoGenerated?: number;
  deletedAt?: string
}

export interface Treatment extends BaseEntity {
  patientId: string;
  visitId?: string
  doctorId: string;
  code: string;
  name: string;
  category: string;
  price: number;
  quantity: number;
  teethNumbers: string[];
  status: TreatmentStatus;
  plannedDate?: string
  completedDate?: string
  remark?: string
}

export interface TreatmentCatalog extends BaseEntity {
  code: string;
  name: string;
  category: string;
  price: number;
  remark?: string
}

export interface Charge extends BaseEntity {
  patientId: string;
  visitId?: string
  doctorId?: string
  number: string;
  totalAmount: number;
  paidAmount: number;
  refundedAmount: number;
  discount: number;
  status: ChargeStatus;
  payMethod?: PayMethod
  paidAt?: string
  remark?: string
  chargeId?: string;
  code?: string;
  isEnabled?: number;
  debtAmount?: number;
  parentId?: string
  balance?: number;
  deletedAt?: string
}

export type EquipmentStatus = 'NORMAL' | 'MAINTENANCE' | 'BROKEN' | 'SCRAPPED';

export interface Equipment extends BaseEntity {
  name: string;
  model?: string
  brand?: string
  serialNumber?: string
  category?: string
  location?: string
  purchasePrice?: number
  purchaseDate?: string
  supplier?: string
  status: EquipmentStatus;
  remarks?: string
}

export { FollowUpStatus } from '../enums';

export interface FollowUp extends BaseEntity {
  patientId: string;
  planDate: string;
  content?: string
  status: FollowUpStatus;
  result?: string
  assigneeId?: string
  completedAt?: string
}

export interface Chair extends BaseEntity {
  name: string;
  location?: string
  active: number;
}

export interface MemberCard extends BaseEntity {
  patientId: string;
  cardNo: string;
  balance: number;
  totalRecharge: number;
  totalConsume: number;
  status: 'ACTIVE' | 'INACTIVE' | 'DISABLED' | 'FROZEN' | 'EXPIRED';
  points: number;
  totalPoints: number;
  level: 'NORMAL' | 'VIP' | 'SVIP';
}

export interface Prescription extends BaseEntity {
  patientId: string;
  visitId?: string
  doctorId: string;
  remark?: string
}

export interface Imaging extends BaseEntity {
  patientId: string;
  visitId?: string
  doctorId?: string
  type: string;
  title: string;
  description?: string
  imageUrl: string;
  thumbnailUrl?: string
  takenAt?: string
  remark?: string
}

export interface Supplier extends BaseEntity {
  code?: string;
  name: string;
  contactPerson?: string;
  phone?: string;
  address?: string;
  bankAccount?: string;
  remark?: string;
}

export interface InventoryItem extends BaseEntity {
  code: string;
  name: string;
  spec?: string
  category: string;
  unit: string;
  stock: number;
  minStock: number;
  price: number;
  supplierId?: string
  expireDate?: string
  location?: string
  remark?: string
}

export interface Registration extends BaseEntity {
  patientId: string;
  doctorId?: string
  type: RegistrationType;
  status: RegistrationStatus;
  visitId?: string
  appointmentId?: string
  triageNote?: string
  chiefComplaint?: string
  registeredBy?: string
  registeredAt: string;
  triagedAt?: string
  startedAt?: string
  completedAt?: string
}

export interface OperationLog extends BaseEntity {
  userId?: string
  userName?: string
  action: string;
  target?: string
  detail?: string
  ip?: string
}

export interface FirstExam extends BaseEntity {
  patientId: string;
  doctorId?: string
  consultantId?: string
  chiefComplaint?: string
  presentIllness?: string
  pastHistory?: string
  oralExam?: string
  auxiliaryExam?: string
  diagnosis?: string
  treatmentSuggestion?: string
  status: string;
  remark?: string
  deletedAt?: string
}

export interface FirstExamTooth {
  id: string;
  examId: string;
  toothNumber: number;
  toothStatus: string;
  diseases: string[];
  isChief: number;
  treatmentPlan?: string
  remark?: string
}

export interface MedicalRecord extends BaseEntity {
  templateId?: string;
  isTemplate?: number;
  category?: string;
  patientId: string;
  visitId?: string
  doctorId?: string
  chiefComplaint?: string
  presentIllness?: string
  pastHistory?: string
  allergyHistory?: string
  examination?: string
  diagnosis?: string
  treatmentPlan?: string
  teethInvolved?: string[];
  images?: string[];
  isLocked?: number;
  lockedAt?: string;
  lockedBy?: string;
  signature?: string;
  modifyRequestId?: string;
  status: string;
  deletedAt?: string
}

export interface ProcessingOrder extends BaseEntity {
  patientId: string;
  visitId?: string
  factoryId?: string
  doctorId?: string
  number: string;
  shade?: string
  teethNumbers: string[];
  totalFee: number;
  status: string;
  chargeId?: string
  sentAt?: string
  expectedAt?: string
  receivedAt?: string
  deliveredAt?: string
  remark?: string
  deletedAt?: string
}

export interface ProcessingOrderItem {
  id: string;
  orderId: string;
  name: string;
  spec?: string
  quantity: number;
  unitPrice: number;
  subtotal: number;
  status: string;
}

export interface BackupRecord {
  id: string;
  filename: string;
  fileSize: number;
  type: string;
  remark?: string
  createdAt: string;
}

export interface WechatMessage extends BaseEntity {
  patientId: string;
  type: string;
  content?: string
  status: string;
  templateId?: string
  sentAt?: string
  result?: string
  remark?: string
  name?: string
  openId?: string
}

export interface Refund extends BaseEntity {
  chargeId: string;
  patientId: string;
  amount: number;
  reason?: string
  operatorId?: string
  operatorName?: string
  deletedAt?: string
}

export interface SmsLog extends BaseEntity {
  patientId?: string
  phone: string;
  content: string;
  type: string;
  status: string;
  result?: string
  sentAt?: string
  cost?: number;
}

export interface Invoice extends BaseEntity {
  chargeId: string;
  patientId: string;
  number: string;
  amount: number;
  type: string;
  status: string;
  issuedAt?: string
  remark?: string
}



// DB row types (runtime fields from database)
export interface ToothRecord extends BaseEntity {
  patientId: string;
  toothNumber: number;
  currentStatus: string;
  conditions: string[];
  remark?: string
  deletedAt?: string
}

export interface TreatmentPlan extends BaseEntity {
  patientId: string;
  visitId?: string
  doctorId: string;
  name: string;
  status: string;
  totalFee: number;
  remark?: string
  deletedAt?: string
}

export interface TreatmentPlanItem {
  id: string;
  code: string;
  name: string;
  category: string;
  price: number;
  quantity: number;
  teethNumbers: string[];
  status: string;
  treatmentId?: string
  completedAt?: string
  remark?: string
}

export interface ChargeItem {
  id: string;
  chargeId: string;
  treatmentId?: string
  name: string;
  category: string;
  price: number;
  quantity: number;
  teethNumbers: string[];
  subtotal: number;
}

export const PATIENT_SOURCE_LABEL: Record<PatientSource, string> = {
  WALK_IN: '上门',
  REFERRAL: '转介绍',
  ONLINE: '线上',
  OTHER: '其他',
};

export const PATIENT_SOURCE_COLOR: Record<PatientSource, string> = {
  WALK_IN: 'bg-primary/10 text-primary',
  REFERRAL: 'bg-success/10 text-success',
  ONLINE: 'bg-info/10 text-info',
  OTHER: 'bg-muted text-muted-foreground',
};

export const APPOINTMENT_STATUS_LABEL: Record<AppointmentStatus, string> = {
  BOOKED: '已预约',
  ARRIVED: '已到店',
  IN_CHAIR: '就诊中',
  COMPLETED: '已完成',
  CANCELLED: '已取消',
  NO_SHOW: '爽约',
};

export const TREATMENT_STATUS_LABEL: Record<TreatmentStatus, string> = {
  PLANNED: '待执行',
  APPROVED: '已确认',
  IN_PROGRESS: '执行中',
  COMPLETED: '已完成',
  CANCELLED: '已取消',
};

export const CHARGE_STATUS_LABEL: Record<ChargeStatus, string> = {
  UNPAID: '未支付',
  PARTIAL: '部分支付',
  PAID: '已支付',
  REFUNDED: '已退款',
  CANCELLED: '已取消',
};

export const EQUIPMENT_STATUS_LABEL: Record<EquipmentStatus, string> = {
  NORMAL: '正常',
  MAINTENANCE: '维修中',
  BROKEN: '故障',
  SCRAPPED: '报废',
};

export const EQUIPMENT_STATUS_COLOR: Record<EquipmentStatus, string> = {
  NORMAL: 'bg-success/10 text-success',
  MAINTENANCE: 'bg-warning/10 text-warning',
  BROKEN: 'bg-destructive/10 text-destructive',
  SCRAPPED: 'bg-muted text-muted-foreground',
};

export const EQUIPMENT_CATEGORIES = [
  '电脑设备',
  '扫描仪',
  '打印机',
  '牙椅设备',
  'X光机',
  'CT机',
  '消毒设备',
  '空气净化',
  '办公家具',
  '其他',
];

// 离线同步相关类型
export type {
  SyncOperation,
  SyncChangeRecord,
  SyncPushChange,
  SyncPushPayload,
  SyncPullResult,
  SyncResult,
  SyncStatus,
} from './sync';
