export const clinicalTables = [
  `CREATE TABLE IF NOT EXISTS Appointment (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT NOT NULL,
      chairId TEXT,
      startTime TEXT NOT NULL,
      endTime TEXT NOT NULL,
      status TEXT DEFAULT 'BOOKED' CHECK (status IN ('BOOKED', 'ARRIVED', 'IN_CHAIR', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
      type TEXT NOT NULL,
      remark TEXT,
      visitId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (chairId) REFERENCES Chair(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Chair (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      location TEXT,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS Visit (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      appointmentId TEXT UNIQUE,
      doctorId TEXT NOT NULL,
      chiefComplaint TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      startTime TEXT DEFAULT CURRENT_TIMESTAMP,
      endTime TEXT,
      status TEXT DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (appointmentId) REFERENCES Appointment(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ToothRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      toothNumber INTEGER NOT NULL CHECK (toothNumber >= 1 AND toothNumber <= 55),
      currentStatus TEXT DEFAULT 'SOUND',
      conditions TEXT DEFAULT '[]',
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(patientId, toothNumber),
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Treatment (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      status TEXT DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      plannedDate TEXT,
      completedDate TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS TreatmentCatalog (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS TreatmentPlan (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      name TEXT NOT NULL,
      status TEXT DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      totalFee REAL DEFAULT 0 CHECK (totalFee >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS TreatmentPlanItem (
      id TEXT PRIMARY KEY,
      planId TEXT NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      status TEXT DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      treatmentId TEXT,
      completedAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      updatedAt TEXT,
      deletedAt TEXT,
      FOREIGN KEY (planId) REFERENCES TreatmentPlan(id) ON DELETE CASCADE,
      FOREIGN KEY (treatmentId) REFERENCES Treatment(id)
    )`,
  `CREATE TABLE IF NOT EXISTS OralExamination (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      examDate TEXT NOT NULL,
      plaqueIndex TEXT,
      calculusIndex TEXT,
      bleedingIndex TEXT,
      caries TEXT DEFAULT '[]',
      looseTeeth TEXT DEFAULT '[]',
      percussionPain TEXT DEFAULT '[]',
      pulpVitality TEXT DEFAULT '[]',
      mucosa TEXT,
      tmj TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS PeriodontalRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      examDate TEXT NOT NULL,
      data TEXT NOT NULL DEFAULT '{}',
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS MedicalRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      templateId TEXT,
      chiefComplaint TEXT,
      presentIllness TEXT,
      pastHistory TEXT,
      allergyHistory TEXT,
      examination TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      teethInvolved TEXT DEFAULT '[]',
      images TEXT DEFAULT '[]',
      signature TEXT,
      isLocked INTEGER DEFAULT 0,
      lockedAt TEXT,
      lockedBy TEXT,
      modifyRequestId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS MedicalRecordTemplate (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      chiefComplaint TEXT,
      presentIllness TEXT,
      pastHistory TEXT,
      examination TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS MedicalRecordPhrase (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      content TEXT NOT NULL,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS RecordModifyRequest (
      id TEXT PRIMARY KEY,
      recordId TEXT NOT NULL,
      applicantId TEXT NOT NULL,
      reason TEXT NOT NULL,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
      reviewerId TEXT,
      reviewRemark TEXT,
      reviewedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (recordId) REFERENCES MedicalRecord(id) ON DELETE CASCADE,
      FOREIGN KEY (applicantId) REFERENCES User(id),
      FOREIGN KEY (reviewerId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS FirstExam (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      consultantId TEXT,
      examDate TEXT DEFAULT CURRENT_TIMESTAMP,
      dentitionType TEXT DEFAULT 'PERMANENT',
      chiefComplaint TEXT,
      diagnosis TEXT,
      treatmentSuggestion TEXT,
      remark TEXT,
      isRestart INTEGER DEFAULT 0,
      parentExamId TEXT,
      status TEXT DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'CANCELLED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (consultantId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS FirstExamTooth (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      toothNumber INTEGER NOT NULL,
      toothStatus TEXT DEFAULT 'SOUND',
      diseases TEXT DEFAULT '[]',
      isChief INTEGER DEFAULT 0,
      treatmentPlan TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS FirstExamTrack (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FOLLOWING', 'TREATING', 'CHURNED', 'CLOSED')),
      leaderSuggestion TEXT,
      directorSuggestion TEXT,
      churnReason TEXT,
      churnSolution TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS FirstExamFollowUp (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      planDate TEXT,
      content TEXT,
      assigneeId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE,
      FOREIGN KEY (assigneeId) REFERENCES User(id)
    )`,
];
