export const financialTables = [
  `CREATE TABLE IF NOT EXISTS Charge (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      number TEXT UNIQUE NOT NULL,
      totalAmount INTEGER NOT NULL CHECK (totalAmount >= 0),
      paidAmount INTEGER DEFAULT 0 CHECK (paidAmount >= 0),
      refundedAmount INTEGER DEFAULT 0 CHECK (refundedAmount >= 0),
      discount INTEGER DEFAULT 0 CHECK (discount >= 0),
      status TEXT DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED', 'CANCELLED')),
      payMethod TEXT,
      paidAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ChargeItem (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL,
      treatmentId TEXT,
      inventoryItemId TEXT,
      consumedQuantity REAL DEFAULT 0,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price INTEGER NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      subtotal INTEGER DEFAULT 0 CHECK (subtotal >= 0),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id) ON DELETE CASCADE,
      FOREIGN KEY (treatmentId) REFERENCES Treatment(id),
      FOREIGN KEY (inventoryItemId) REFERENCES InventoryItem(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ChargeCombo (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS ChargeComboItem (
      id TEXT PRIMARY KEY,
      comboId TEXT NOT NULL,
      treatmentCatalogId TEXT,
      itemName TEXT NOT NULL,
      price INTEGER DEFAULT 0,
      quantity INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (comboId) REFERENCES ChargeCombo(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS PaymentMethod (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code TEXT UNIQUE NOT NULL,
      parentId TEXT,
      sortOrder INTEGER DEFAULT 0,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS DebtRecord (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL UNIQUE,
      patientId TEXT NOT NULL,
      totalAmount INTEGER NOT NULL,
      paidAmount INTEGER DEFAULT 0 CHECK (paidAmount >= 0),
      debtAmount INTEGER NOT NULL CHECK (debtAmount >= 0),
      status TEXT DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED')),
      lastPaymentAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Refund (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      amount INTEGER NOT NULL CHECK (amount > 0),
      reason TEXT,
      operatorId TEXT,
      operatorName TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS MemberCard (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      cardNo TEXT UNIQUE NOT NULL,
      balance INTEGER DEFAULT 0 CHECK (balance >= 0),
      totalRecharge INTEGER DEFAULT 0 CHECK (totalRecharge >= 0),
      totalConsume INTEGER DEFAULT 0 CHECK (totalConsume >= 0),
      points INTEGER DEFAULT 0,
      totalPoints INTEGER DEFAULT 0,
      level TEXT DEFAULT 'NORMAL',
      status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED', 'FROZEN', 'EXPIRED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    )`,
  `CREATE TABLE IF NOT EXISTS MemberCardLog (
      id TEXT PRIMARY KEY,
      cardId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('RECHARGE', 'CONSUME', 'REFUND')),
      amount INTEGER NOT NULL,
      balanceAfter INTEGER,
      chargeId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (cardId) REFERENCES MemberCard(id) ON DELETE CASCADE,
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    )`,
  `CREATE TABLE IF NOT EXISTS MemberPointLog (
      id TEXT PRIMARY KEY,
      cardId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('ADD', 'DEDUCT')),
      points INTEGER NOT NULL,
      balanceAfter INTEGER,
      chargeId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (cardId) REFERENCES MemberCard(id) ON DELETE CASCADE,
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    )`,
];
