export const inventoryTables = [
  `CREATE TABLE IF NOT EXISTS Supplier (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      contactPerson TEXT,
      phone TEXT,
      address TEXT,
      bankAccount TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS InventoryItem (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      spec TEXT,
      category TEXT NOT NULL,
      unit TEXT NOT NULL,
      stock REAL DEFAULT 0 CHECK (stock >= 0),
      minStock REAL DEFAULT 0 CHECK (minStock >= 0),
      price INTEGER DEFAULT 0,
      supplierId TEXT,
      expireDate TEXT,
      location TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id)
    )`,
  `CREATE TABLE IF NOT EXISTS InventoryTransaction (
      id TEXT PRIMARY KEY,
      itemId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('IN', 'OUT', 'ADJUST')),
      quantity REAL NOT NULL CHECK (quantity >= 0),
      unitPrice INTEGER DEFAULT 0,
      totalAmount INTEGER DEFAULT 0,
      supplierId TEXT,
      purchaseOrderId TEXT,
      operatorId TEXT,
      operatorName TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (itemId) REFERENCES InventoryItem(id),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS PurchaseOrder (
      id TEXT PRIMARY KEY,
      number TEXT NOT NULL,
      supplierId TEXT NOT NULL,
      totalAmount INTEGER DEFAULT 0,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PARTIAL', 'RECEIVED', 'CANCELLED')),
      operatorId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, number),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS PurchaseOrderItem (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      itemId TEXT,
      name TEXT NOT NULL,
      spec TEXT,
      quantity REAL NOT NULL,
      unitPrice INTEGER NOT NULL,
      subtotal INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES PurchaseOrder(id) ON DELETE CASCADE,
      FOREIGN KEY (itemId) REFERENCES InventoryItem(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Equipment (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      model TEXT,
      brand TEXT,
      serialNumber TEXT,
      category TEXT,
      location TEXT,
      purchasePrice INTEGER,
      purchaseDate TEXT,
      supplier TEXT,
      status TEXT DEFAULT 'NORMAL' CHECK (status IN ('NORMAL', 'MAINTENANCE', 'BROKEN', 'SCRAPPED')),
      remarks TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS ProcessingFactory (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      contactPerson TEXT,
      phone TEXT,
      address TEXT,
      remark TEXT,
      status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS ProcessingProduct (
      id TEXT PRIMARY KEY,
      factoryId TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT,
      price INTEGER DEFAULT 0,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (factoryId) REFERENCES ProcessingFactory(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ProcessingOrder (
      id TEXT PRIMARY KEY,
      number TEXT NOT NULL,
      patientId TEXT NOT NULL,
      visitId TEXT,
      factoryId TEXT NOT NULL,
      doctorId TEXT,
      shade TEXT,
      teethNumbers TEXT DEFAULT '[]',
      totalFee INTEGER DEFAULT 0,
      status TEXT DEFAULT 'SENT' CHECK (status IN ('PENDING', 'SENT', 'IN_PROGRESS', 'COMPLETED', 'RECEIVED', 'CANCELLED')),
      chargeId TEXT,
      sentAt TEXT,
      expectedAt TEXT,
      receivedAt TEXT,
      deliveredAt TEXT,
      remark TEXT,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, number),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (factoryId) REFERENCES ProcessingFactory(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ProcessingOrderItem (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      productId TEXT,
      productName TEXT NOT NULL,
      toothNumber INTEGER,
      quantity INTEGER DEFAULT 1,
      unitPrice INTEGER DEFAULT 0,
      subtotal INTEGER DEFAULT 0,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES ProcessingOrder(id) ON DELETE CASCADE,
      FOREIGN KEY (productId) REFERENCES ProcessingProduct(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ProcessingFlowLog (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      status TEXT NOT NULL,
      remark TEXT,
      operatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES ProcessingOrder(id) ON DELETE CASCADE
    )`,
];
