export const patientTables = [
  `CREATE TABLE IF NOT EXISTS Patient (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      gender TEXT NOT NULL CHECK (gender IN ('MALE','FEMALE','UNKNOWN','OTHER')),
      birthDate TEXT,
      phone TEXT NOT NULL,
      idCard TEXT,
      address TEXT,
      occupation TEXT,
      remark TEXT,
      avatar TEXT,
      tags TEXT DEFAULT '[]',
      allergies TEXT DEFAULT '[]',
      medicalHistory TEXT DEFAULT '[]',
      medicationHistory TEXT DEFAULT '[]',
      systemicDiseases TEXT DEFAULT '[]',
      source TEXT DEFAULT 'WALK_IN',
      familyId TEXT,
      referrer TEXT,
      emergencyContact TEXT,
      emergencyPhone TEXT,
      openId TEXT,
      clinicId TEXT NOT NULL,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (familyId) REFERENCES Family(id),
      FOREIGN KEY (clinicId) REFERENCES Clinic(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Family (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS FollowUp (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      planDate TEXT NOT NULL,
      content TEXT,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_ANSWER')),
      result TEXT,
      assigneeId TEXT,
      completedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (assigneeId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS FollowUpTemplate (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      type TEXT,
      daysAfter INTEGER DEFAULT 1,
      content TEXT,
      assigneeId TEXT,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS FollowUpItem (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      templateId TEXT,
      sortOrder INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS FollowUpResult (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      sortOrder INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS AutoFollowUpRule (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      triggerType TEXT,
      triggerDays INTEGER DEFAULT 1,
      templateId TEXT,
      assigneeId TEXT,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (templateId) REFERENCES FollowUpTemplate(id)
    )`,
  `CREATE TABLE IF NOT EXISTS Registration (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      type TEXT NOT NULL,
      status TEXT DEFAULT 'REGISTERED' CHECK (status IN ('REGISTERED', 'TRIAGED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      visitId TEXT,
      appointmentId TEXT,
      triageNote TEXT,
      chiefComplaint TEXT,
      registeredBy TEXT,
      registeredAt TEXT DEFAULT CURRENT_TIMESTAMP,
      triagedAt TEXT,
      startedAt TEXT,
      completedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (appointmentId) REFERENCES Appointment(id)
    )`,
];
