export const pharmacyTables = [
  `CREATE TABLE IF NOT EXISTS DrugCatalog (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      spec TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      unit TEXT NOT NULL,
      stock REAL DEFAULT 0 CHECK (stock >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, code)
    )`,
  `CREATE TABLE IF NOT EXISTS Prescription (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS PrescriptionItem (
      id TEXT PRIMARY KEY,
      prescriptionId TEXT NOT NULL,
      drugCode TEXT,
      drugName TEXT NOT NULL,
      spec TEXT NOT NULL,
      dosage TEXT NOT NULL,
      frequency TEXT NOT NULL,
      days INTEGER NOT NULL CHECK (days >= 1),
      quantity REAL NOT NULL CHECK (quantity >= 0),
      unit TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (prescriptionId) REFERENCES Prescription(id) ON DELETE CASCADE
    )`,
  `CREATE TABLE IF NOT EXISTS Imaging (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT,
      imageUrl TEXT NOT NULL,
      thumbnailUrl TEXT,
      takenAt TEXT DEFAULT CURRENT_TIMESTAMP,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
];
