export const analyticsTables = [
  `CREATE TABLE IF NOT EXISTS PatientRfmScore (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      recencyDays INTEGER,
      frequency INTEGER,
      monetary INTEGER,
      rScore INTEGER CHECK (rScore BETWEEN 1 AND 5),
      fScore INTEGER CHECK (fScore BETWEEN 1 AND 5),
      mScore INTEGER CHECK (mScore BETWEEN 1 AND 5),
      rfmScore TEXT NOT NULL,
      segment TEXT NOT NULL,
      churnProbability REAL CHECK (churnProbability BETWEEN 0 AND 1),
      computedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, patientId),
      FOREIGN KEY(patientId) REFERENCES Patient(id)
    )`,
  `CREATE TABLE IF NOT EXISTS DoctorPerformanceAnomaly (
      id TEXT PRIMARY KEY,
      doctorId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      metric TEXT NOT NULL CHECK (metric IN ('REVENUE_30D', 'VISITS_30D', 'NO_SHOW_RATE_30D', 'AVG_AOV_30D')),
      baselineMean REAL NOT NULL,
      baselineStd REAL NOT NULL,
      sampleSize INTEGER,
      currentValue REAL NOT NULL,
      zScore REAL NOT NULL,
      severity TEXT NOT NULL CHECK (severity IN ('INFO', 'WARN', 'CRITICAL')),
      detectedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      detectedAtDate TEXT,
      resolvedAt TEXT,
      note TEXT,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, doctorId, metric, detectedAtDate)
    )`,
  `CREATE TABLE IF NOT EXISTS TreatmentProgressSnapshot (
      id TEXT PRIMARY KEY,
      planId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      plannedItems INTEGER NOT NULL DEFAULT 0,
      completedItems INTEGER NOT NULL DEFAULT 0,
      inProgressItems INTEGER NOT NULL DEFAULT 0,
      cancelledItems INTEGER NOT NULL DEFAULT 0,
      skippedItems INTEGER NOT NULL DEFAULT 0,
      plannedTotalFee INTEGER NOT NULL DEFAULT 0,
      chargedAmount INTEGER NOT NULL DEFAULT 0,
      completionPercent REAL NOT NULL DEFAULT 0,
      overdueDays INTEGER NOT NULL DEFAULT 0,
      behindSchedule INTEGER DEFAULT 0 CHECK (behindSchedule IN (0,1)),
      snapshotDate TEXT NOT NULL,
      snapshotJson TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(planId, snapshotDate)
    )`,
  `CREATE TABLE IF NOT EXISTS SatisfactionSurvey (
      id TEXT PRIMARY KEY,
      visitId TEXT UNIQUE,
      appointmentId TEXT,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      npsScore INTEGER NOT NULL CHECK (npsScore BETWEEN 0 AND 10),
      ratingMedical INTEGER CHECK (ratingMedical BETWEEN 1 AND 5),
      ratingService INTEGER CHECK (ratingService BETWEEN 1 AND 5),
      ratingEnvironment INTEGER CHECK (ratingEnvironment BETWEEN 1 AND 5),
      ratingPrice INTEGER CHECK (ratingPrice BETWEEN 1 AND 5),
      ratingWait INTEGER CHECK (ratingWait BETWEEN 1 AND 5),
      comment TEXT,
      tags TEXT DEFAULT '[]',
      source TEXT DEFAULT 'CLINIC' CHECK (source IN ('CLINIC','QR_CODE','SMS_LINK','FOLLOW_UP_CALL')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS NpsSnapshot (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      snapshotDate TEXT NOT NULL,
      totalResponses INTEGER NOT NULL,
      promoters INTEGER NOT NULL,
      detractors INTEGER NOT NULL,
      passives INTEGER NOT NULL,
      nps REAL NOT NULL,
      avgRatingMedical REAL,
      avgRatingService REAL,
      avgRatingEnvironment REAL,
      avgRatingPrice REAL,
      avgRatingWait REAL,
      negativeKeywordCount TEXT DEFAULT '{}',
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, snapshotDate)
    )`,
];
