CREATE TABLE IF NOT EXISTS PatientRfmScore (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      recencyDays INTEGER,
      frequency INTEGER,
      monetary INTEGER,
      rScore INTEGER CHECK (rScore BETWEEN 1 AND 5),
      fScore INTEGER CHECK (fScore BETWEEN 1 AND 5),
      mScore INTEGER CHECK (mScore BETWEEN 1 AND 5),
      rfmScore TEXT NOT NULL,
      segment TEXT NOT NULL,
      churnProbability REAL CHECK (churnProbability BETWEEN 0 AND 1),
      computedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, patientId),
      FOREIGN KEY(patientId) REFERENCES Patient(id)
    );
CREATE TABLE IF NOT EXISTS DoctorPerformanceAnomaly (
      id TEXT PRIMARY KEY,
      doctorId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      metric TEXT NOT NULL CHECK (metric IN ('REVENUE_30D', 'VISITS_30D', 'NO_SHOW_RATE_30D', 'AVG_AOV_30D')),
      baselineMean REAL NOT NULL,
      baselineStd REAL NOT NULL,
      sampleSize INTEGER,
      currentValue REAL NOT NULL,
      zScore REAL NOT NULL,
      severity TEXT NOT NULL CHECK (severity IN ('INFO', 'WARN', 'CRITICAL')),
      detectedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      detectedAtDate TEXT,
      resolvedAt TEXT,
      note TEXT,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, doctorId, metric, detectedAtDate)
    );
CREATE TABLE IF NOT EXISTS TreatmentProgressSnapshot (
      id TEXT PRIMARY KEY,
      planId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      plannedItems INTEGER NOT NULL DEFAULT 0,
      completedItems INTEGER NOT NULL DEFAULT 0,
      inProgressItems INTEGER NOT NULL DEFAULT 0,
      cancelledItems INTEGER NOT NULL DEFAULT 0,
      skippedItems INTEGER NOT NULL DEFAULT 0,
      plannedTotalFee INTEGER NOT NULL DEFAULT 0,
      chargedAmount INTEGER NOT NULL DEFAULT 0,
      completionPercent REAL NOT NULL DEFAULT 0,
      overdueDays INTEGER NOT NULL DEFAULT 0,
      behindSchedule INTEGER DEFAULT 0 CHECK (behindSchedule IN (0,1)),
      snapshotDate TEXT NOT NULL,
      snapshotJson TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(planId, snapshotDate)
    );
CREATE TABLE IF NOT EXISTS SatisfactionSurvey (
      id TEXT PRIMARY KEY,
      visitId TEXT UNIQUE,
      appointmentId TEXT,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      npsScore INTEGER NOT NULL CHECK (npsScore BETWEEN 0 AND 10),
      ratingMedical INTEGER CHECK (ratingMedical BETWEEN 1 AND 5),
      ratingService INTEGER CHECK (ratingService BETWEEN 1 AND 5),
      ratingEnvironment INTEGER CHECK (ratingEnvironment BETWEEN 1 AND 5),
      ratingPrice INTEGER CHECK (ratingPrice BETWEEN 1 AND 5),
      ratingWait INTEGER CHECK (ratingWait BETWEEN 1 AND 5),
      comment TEXT,
      tags TEXT DEFAULT '[]',
      source TEXT DEFAULT 'CLINIC' CHECK (source IN ('CLINIC','QR_CODE','SMS_LINK','FOLLOW_UP_CALL')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS NpsSnapshot (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      snapshotDate TEXT NOT NULL,
      totalResponses INTEGER NOT NULL,
      promoters INTEGER NOT NULL,
      detractors INTEGER NOT NULL,
      passives INTEGER NOT NULL,
      nps REAL NOT NULL,
      avgRatingMedical REAL,
      avgRatingService REAL,
      avgRatingEnvironment REAL,
      avgRatingPrice REAL,
      avgRatingWait REAL,
      negativeKeywordCount TEXT DEFAULT '{}',
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, snapshotDate)
    );
CREATE TABLE IF NOT EXISTS Appointment (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT NOT NULL,
      chairId TEXT,
      startTime TEXT NOT NULL,
      endTime TEXT NOT NULL,
      status TEXT DEFAULT 'BOOKED' CHECK (status IN ('BOOKED', 'ARRIVED', 'IN_CHAIR', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
      type TEXT NOT NULL,
      remark TEXT,
      visitId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (chairId) REFERENCES Chair(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id)
    );
CREATE TABLE IF NOT EXISTS Chair (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      location TEXT,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS Visit (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      appointmentId TEXT UNIQUE,
      doctorId TEXT NOT NULL,
      chiefComplaint TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      summary TEXT,
      startTime TEXT DEFAULT CURRENT_TIMESTAMP,
      endTime TEXT,
      status TEXT DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      nextReminder TEXT,
      summaryAutoGenerated INTEGER DEFAULT 0 CHECK(summaryAutoGenerated IN (0,1)),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (appointmentId) REFERENCES Appointment(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS ToothRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      toothNumber INTEGER NOT NULL CHECK (toothNumber >= 1 AND toothNumber <= 55),
      currentStatus TEXT DEFAULT 'SOUND',
      conditions TEXT DEFAULT '[]',
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(patientId, toothNumber),
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    );
CREATE TABLE IF NOT EXISTS Treatment (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      status TEXT DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      plannedDate TEXT,
      completedDate TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS TreatmentCatalog (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code)
    );
CREATE TABLE IF NOT EXISTS TreatmentPlan (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      name TEXT NOT NULL,
      status TEXT DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      totalFee INTEGER DEFAULT 0 CHECK (totalFee >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS TreatmentPlanItem (
      id TEXT PRIMARY KEY,
      planId TEXT NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price INTEGER NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      status TEXT DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'SKIPPED')),
      treatmentId TEXT,
      completedAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      updatedAt TEXT,
      deletedAt TEXT,
      FOREIGN KEY (planId) REFERENCES TreatmentPlan(id) ON DELETE CASCADE,
      FOREIGN KEY (treatmentId) REFERENCES Treatment(id)
    );
CREATE TABLE IF NOT EXISTS TreatmentProgressSnapshot (
      id TEXT PRIMARY KEY,
      planId TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      plannedItems INTEGER NOT NULL DEFAULT 0,
      completedItems INTEGER NOT NULL DEFAULT 0,
      inProgressItems INTEGER NOT NULL DEFAULT 0,
      cancelledItems INTEGER NOT NULL DEFAULT 0,
      skippedItems INTEGER NOT NULL DEFAULT 0,
      plannedTotalFee INTEGER NOT NULL DEFAULT 0,
      chargedAmount INTEGER NOT NULL DEFAULT 0,
      completionPercent REAL NOT NULL DEFAULT 0,
      overdueDays INTEGER NOT NULL DEFAULT 0,
      behindSchedule INTEGER DEFAULT 0 CHECK (behindSchedule IN (0,1)),
      snapshotDate TEXT NOT NULL,
      snapshotJson TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(planId, snapshotDate)
    );
CREATE TABLE IF NOT EXISTS OralExamination (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      examDate TEXT NOT NULL,
      plaqueIndex TEXT,
      calculusIndex TEXT,
      bleedingIndex TEXT,
      caries TEXT DEFAULT '[]',
      looseTeeth TEXT DEFAULT '[]',
      percussionPain TEXT DEFAULT '[]',
      pulpVitality TEXT DEFAULT '[]',
      mucosa TEXT,
      tmj TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS PeriodontalRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      examDate TEXT NOT NULL,
      data TEXT NOT NULL DEFAULT '{}',
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS MedicalRecord (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      templateId TEXT,
      chiefComplaint TEXT,
      presentIllness TEXT,
      pastHistory TEXT,
      allergyHistory TEXT,
      examination TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      teethInvolved TEXT DEFAULT '[]',
      images TEXT DEFAULT '[]',
      signature TEXT,
      isLocked INTEGER DEFAULT 0,
      lockedAt TEXT,
      lockedBy TEXT,
      modifyRequestId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS MedicalRecordTemplate (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      chiefComplaint TEXT,
      presentIllness TEXT,
      pastHistory TEXT,
      examination TEXT,
      diagnosis TEXT,
      treatmentPlan TEXT,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS MedicalRecordPhrase (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      content TEXT NOT NULL,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      ownerId TEXT,
      pinOrder INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS RecordModifyRequest (
      id TEXT PRIMARY KEY,
      recordId TEXT NOT NULL,
      applicantId TEXT NOT NULL,
      reason TEXT NOT NULL,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
      reviewerId TEXT,
      reviewRemark TEXT,
      reviewedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (recordId) REFERENCES MedicalRecord(id) ON DELETE CASCADE,
      FOREIGN KEY (applicantId) REFERENCES User(id),
      FOREIGN KEY (reviewerId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS FirstExam (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      consultantId TEXT,
      examDate TEXT DEFAULT CURRENT_TIMESTAMP,
      dentitionType TEXT DEFAULT 'PERMANENT',
      chiefComplaint TEXT,
      diagnosis TEXT,
      treatmentSuggestion TEXT,
      remark TEXT,
      isRestart INTEGER DEFAULT 0,
      parentExamId TEXT,
      status TEXT DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'CANCELLED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (consultantId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS FirstExamTooth (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      toothNumber INTEGER NOT NULL,
      toothStatus TEXT DEFAULT 'SOUND',
      diseases TEXT DEFAULT '[]',
      isChief INTEGER DEFAULT 0,
      treatmentPlan TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS FirstExamTrack (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'FOLLOWING', 'TREATING', 'CHURNED', 'CLOSED')),
      leaderSuggestion TEXT,
      directorSuggestion TEXT,
      churnReason TEXT,
      churnSolution TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS FirstExamFollowUp (
      id TEXT PRIMARY KEY,
      examId TEXT NOT NULL,
      planDate TEXT,
      content TEXT,
      assigneeId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (examId) REFERENCES FirstExam(id) ON DELETE CASCADE,
      FOREIGN KEY (assigneeId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS CephalometricLandmarkSet (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      imageId TEXT,
      landmarkJson TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, patientId, imageId),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (imageId) REFERENCES Imaging(id)
    );
CREATE TABLE IF NOT EXISTS CephalometricAnalysisRecord (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      landmarkSetId TEXT NOT NULL,
      method TEXT NOT NULL CHECK(method IN ('TWEED','MCNAMARA','STEINER','DOWNS')),
      metricsJson TEXT NOT NULL,
      analysisDate TEXT NOT NULL,
      doctorId TEXT,
      remark TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, landmarkSetId, method),
      FOREIGN KEY (landmarkSetId) REFERENCES CephalometricLandmarkSet(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS CephalometricNormValue (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      method TEXT NOT NULL,
      metricName TEXT NOT NULL,
      race TEXT DEFAULT 'CHINESE',
      gender TEXT CHECK(gender IN ('MALE','FEMALE','BOTH')) DEFAULT 'BOTH',
      ageMin INTEGER,
      ageMax INTEGER,
      mean REAL NOT NULL,
      stdDev REAL NOT NULL,
      unit TEXT,
      source TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS PatientRiskScore (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      cariesScore INTEGER NOT NULL,
      periodontalScore INTEGER NOT NULL,
      implantScore INTEGER NOT NULL,
      cariesLevel TEXT CHECK(cariesLevel IN ('LOW','MEDIUM','HIGH','EXTREME')),
      periodontalLevel TEXT CHECK(periodontalLevel IN ('LOW','MEDIUM','HIGH','EXTREME')),
      implantLevel TEXT CHECK(implantLevel IN ('LOW','MEDIUM','HIGH','EXTREME')),
      factorSnapshotJson TEXT NOT NULL,
      assessedById TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (assessedById) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS SatisfactionSurvey (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      visitId TEXT NOT NULL UNIQUE,
      patientId TEXT NOT NULL,
      npsScore INTEGER CHECK(npsScore BETWEEN 0 AND 10),
      overallStars INTEGER CHECK(overallStars BETWEEN 1 AND 5),
      techStars INTEGER CHECK(techStars BETWEEN 1 AND 5),
      serviceStars INTEGER CHECK(serviceStars BETWEEN 1 AND 5),
      envStars INTEGER CHECK(envStars BETWEEN 1 AND 5),
      comment TEXT,
      tags TEXT DEFAULT '[]',
      doctorId TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS CephalometricAnalysis (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      imagingId TEXT,
      doctorId TEXT,
      name TEXT NOT NULL,
      landmarks TEXT NOT NULL,
      landmarksValidated INTEGER DEFAULT 0 CHECK (landmarksValidated IN (0,1)),
      referencePlanes TEXT NOT NULL,
      measurements TEXT NOT NULL,
      classification TEXT NOT NULL,
      comparisonTemplate TEXT,
      comparisonResult TEXT,
      notes TEXT,
      clinicId TEXT NOT NULL,
      createdBy TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY(patientId) REFERENCES Patient(id)
    );
CREATE TABLE IF NOT EXISTS FollowUpAssignment (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      followUpId TEXT,
      templateId TEXT,
      recommendedDate TEXT,
      actualDate TEXT,
      reason TEXT,
      confidence REAL DEFAULT 0,
      createdBy TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (followUpId) REFERENCES FollowUp(id),
      FOREIGN KEY (templateId) REFERENCES FollowUpTemplate(id)
    );
CREATE TABLE IF NOT EXISTS Charge (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      number TEXT NOT NULL,
      totalAmount INTEGER NOT NULL CHECK (totalAmount >= 0),
      paidAmount INTEGER DEFAULT 0 CHECK (paidAmount >= 0),
      refundedAmount INTEGER DEFAULT 0 CHECK (refundedAmount >= 0),
      discount INTEGER DEFAULT 0 CHECK (discount >= 0),
      status TEXT DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED', 'CANCELLED')),
      payMethod TEXT,
      paidAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, number),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS ChargeItem (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL,
      treatmentId TEXT,
      inventoryItemId TEXT,
      consumedQuantity REAL DEFAULT 0,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      price INTEGER NOT NULL CHECK (price >= 0),
      quantity INTEGER DEFAULT 1 CHECK (quantity >= 1),
      teethNumbers TEXT DEFAULT '[]',
      subtotal INTEGER DEFAULT 0 CHECK (subtotal >= 0),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id) ON DELETE CASCADE,
      FOREIGN KEY (treatmentId) REFERENCES Treatment(id),
      FOREIGN KEY (inventoryItemId) REFERENCES InventoryItem(id)
    );
CREATE TABLE IF NOT EXISTS ChargeCombo (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      isPublic INTEGER DEFAULT 1,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS ChargeComboItem (
      id TEXT PRIMARY KEY,
      comboId TEXT NOT NULL,
      treatmentCatalogId TEXT,
      itemName TEXT NOT NULL,
      price INTEGER DEFAULT 0,
      quantity INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (comboId) REFERENCES ChargeCombo(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS PaymentMethod (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code TEXT UNIQUE NOT NULL,
      parentId TEXT,
      sortOrder INTEGER DEFAULT 0,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS DebtRecord (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL UNIQUE,
      patientId TEXT NOT NULL,
      totalAmount INTEGER NOT NULL,
      paidAmount INTEGER DEFAULT 0 CHECK (paidAmount >= 0),
      debtAmount INTEGER NOT NULL CHECK (debtAmount >= 0),
      status TEXT DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'CANCELLED')),
      lastPaymentAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    );
CREATE TABLE IF NOT EXISTS DebtPayment (
      id TEXT PRIMARY KEY,
      debtId TEXT NOT NULL,
      amount INTEGER NOT NULL CHECK (amount > 0),
      payMethod TEXT NOT NULL,
      paidAt TEXT DEFAULT CURRENT_TIMESTAMP,
      operatorId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      FOREIGN KEY (debtId) REFERENCES DebtRecord(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS Refund (
      id TEXT PRIMARY KEY,
      chargeId TEXT NOT NULL,
      patientId TEXT NOT NULL,
      amount INTEGER NOT NULL CHECK (amount > 0),
      reason TEXT,
      operatorId TEXT,
      operatorName TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (chargeId) REFERENCES Charge(id),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS MemberCard (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      cardNo TEXT NOT NULL,
      balance INTEGER DEFAULT 0 CHECK (balance >= 0),
      totalRecharge INTEGER DEFAULT 0 CHECK (totalRecharge >= 0),
      totalConsume INTEGER DEFAULT 0 CHECK (totalConsume >= 0),
      points INTEGER DEFAULT 0,
      totalPoints INTEGER DEFAULT 0,
      level TEXT DEFAULT 'NORMAL',
      status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED', 'FROZEN', 'EXPIRED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, cardNo),
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    );
CREATE TABLE IF NOT EXISTS MemberCardLog (
      id TEXT PRIMARY KEY,
      cardId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('RECHARGE', 'CONSUME', 'REFUND')),
      amount INTEGER NOT NULL,
      balanceAfter INTEGER,
      chargeId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (cardId) REFERENCES MemberCard(id) ON DELETE CASCADE,
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    );
CREATE TABLE IF NOT EXISTS MemberPointLog (
      id TEXT PRIMARY KEY,
      cardId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('ADD', 'DEDUCT')),
      points INTEGER NOT NULL,
      balanceAfter INTEGER,
      chargeId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (cardId) REFERENCES MemberCard(id) ON DELETE CASCADE,
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    );
CREATE TABLE IF NOT EXISTS ChargeAssociationRule (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      antecedent TEXT NOT NULL,
      consequent TEXT NOT NULL,
      antecedentSize INTEGER NOT NULL CHECK (antecedentSize >= 1),
      support REAL NOT NULL CHECK (support >= 0 AND support <= 1),
      confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
      lift REAL NOT NULL,
      supportCount INTEGER NOT NULL DEFAULT 0 CHECK (supportCount >= 0),
      totalTransactions INTEGER NOT NULL DEFAULT 0,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      computedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, antecedent, consequent)
    );
CREATE TABLE IF NOT EXISTS ChargeAssociationIgnore (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      antecedent TEXT NOT NULL,
      consequent TEXT NOT NULL,
      ignoredAt TEXT DEFAULT CURRENT_TIMESTAMP,
      ignoredBy TEXT NOT NULL,
      UNIQUE(clinicId, antecedent, consequent)
    );
CREATE TABLE IF NOT EXISTS WorkSchedule (
      id TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      shiftType TEXT NOT NULL CHECK (shiftType IN ('MORNING','AFTERNOON','FULL','CUSTOM','LEAVE','OFF')),
      startAt TEXT NOT NULL,
      endAt TEXT NOT NULL,
      note TEXT,
      repeatRule TEXT DEFAULT NULL,
      color TEXT DEFAULT '#4F46E5',
      clinicId TEXT NOT NULL,
      createdBy TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY(userId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS LeaveRequest (
      id TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      leaveType TEXT NOT NULL CHECK (leaveType IN ('ANNUAL','SICK','PERSONAL','MARRIAGE','MATERNITY','PATERNITY','BEREAVEMENT','OTHER')),
      startAt TEXT NOT NULL,
      endAt TEXT NOT NULL,
      totalDays REAL NOT NULL DEFAULT 1,
      reason TEXT,
      status TEXT NOT NULL CHECK (status IN ('SAVED','PENDING','APPROVED','REJECTED','CANCELLED')),
      submittedAt TEXT,
      approverId TEXT,
      approvedAt TEXT,
      rejectReason TEXT,
      clinicId TEXT NOT NULL,
      createdBy TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY(userId) REFERENCES User(id),
      FOREIGN KEY(approverId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS Supplier (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      contactPerson TEXT,
      phone TEXT,
      address TEXT,
      bankAccount TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS InventoryItem (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      spec TEXT,
      category TEXT NOT NULL,
      unit TEXT NOT NULL,
      stock REAL DEFAULT 0 CHECK (stock >= 0),
      minStock REAL DEFAULT 0 CHECK (minStock >= 0),
      price INTEGER DEFAULT 0,
      supplierId TEXT,
      expireDate TEXT,
      location TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id)
    );
CREATE TABLE IF NOT EXISTS InventoryTransaction (
      id TEXT PRIMARY KEY,
      itemId TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('IN', 'OUT', 'ADJUST')),
      quantity REAL NOT NULL CHECK (quantity >= 0),
      unitPrice INTEGER DEFAULT 0,
      totalAmount INTEGER DEFAULT 0,
      supplierId TEXT,
      purchaseOrderId TEXT,
      operatorId TEXT,
      operatorName TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (itemId) REFERENCES InventoryItem(id),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS PurchaseOrder (
      id TEXT PRIMARY KEY,
      number TEXT NOT NULL,
      supplierId TEXT NOT NULL,
      totalAmount INTEGER DEFAULT 0,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PARTIAL', 'RECEIVED', 'CANCELLED')),
      operatorId TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, number),
      FOREIGN KEY (supplierId) REFERENCES Supplier(id),
      FOREIGN KEY (operatorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS PurchaseOrderItem (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      itemId TEXT,
      name TEXT NOT NULL,
      spec TEXT,
      quantity REAL NOT NULL,
      unitPrice INTEGER NOT NULL,
      subtotal INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES PurchaseOrder(id) ON DELETE CASCADE,
      FOREIGN KEY (itemId) REFERENCES InventoryItem(id)
    );
CREATE TABLE IF NOT EXISTS Equipment (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      model TEXT,
      brand TEXT,
      serialNumber TEXT,
      category TEXT,
      location TEXT,
      purchasePrice INTEGER,
      purchaseDate TEXT,
      supplier TEXT,
      status TEXT DEFAULT 'NORMAL' CHECK (status IN ('NORMAL', 'MAINTENANCE', 'BROKEN', 'SCRAPPED')),
      remarks TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS ProcessingFactory (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      contactPerson TEXT,
      phone TEXT,
      address TEXT,
      remark TEXT,
      status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS ProcessingProduct (
      id TEXT PRIMARY KEY,
      factoryId TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT,
      price INTEGER DEFAULT 0,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (factoryId) REFERENCES ProcessingFactory(id)
    );
CREATE TABLE IF NOT EXISTS ProcessingOrder (
      id TEXT PRIMARY KEY,
      number TEXT NOT NULL,
      patientId TEXT NOT NULL,
      visitId TEXT,
      factoryId TEXT NOT NULL,
      doctorId TEXT,
      shade TEXT,
      teethNumbers TEXT DEFAULT '[]',
      totalFee INTEGER DEFAULT 0,
      status TEXT DEFAULT 'SENT' CHECK (status IN ('PENDING', 'SENT', 'IN_PROGRESS', 'COMPLETED', 'RECEIVED', 'CANCELLED')),
      chargeId TEXT,
      sentAt TEXT,
      expectedAt TEXT,
      receivedAt TEXT,
      deliveredAt TEXT,
      remark TEXT,
      creatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, number),
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (factoryId) REFERENCES ProcessingFactory(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (chargeId) REFERENCES Charge(id)
    );
CREATE TABLE IF NOT EXISTS ProcessingOrderItem (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      productId TEXT,
      productName TEXT NOT NULL,
      toothNumber INTEGER,
      quantity INTEGER DEFAULT 1,
      unitPrice INTEGER DEFAULT 0,
      subtotal INTEGER DEFAULT 0,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES ProcessingOrder(id) ON DELETE CASCADE,
      FOREIGN KEY (productId) REFERENCES ProcessingProduct(id)
    );
CREATE TABLE IF NOT EXISTS ProcessingFlowLog (
      id TEXT PRIMARY KEY,
      orderId TEXT NOT NULL,
      status TEXT NOT NULL,
      remark TEXT,
      operatorId TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (orderId) REFERENCES ProcessingOrder(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS InventoryReplenishmentSuggestion (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      inventoryId TEXT NOT NULL,
      avgDailyConsumption REAL,
      leadTimeDays INTEGER DEFAULT 7,
      safetyFactor REAL DEFAULT 1.5,
      rop REAL NOT NULL,
      suggestedQty INTEGER NOT NULL,
      calculationSnapshotJson TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (inventoryId) REFERENCES InventoryItem(id)
    );
CREATE TABLE IF NOT EXISTS Patient (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      gender TEXT NOT NULL CHECK (gender IN ('MALE','FEMALE','UNKNOWN','OTHER')),
      birthDate TEXT,
      phone TEXT NOT NULL,
      idCard TEXT,
      address TEXT,
      occupation TEXT,
      remark TEXT,
      avatar TEXT,
      tags TEXT DEFAULT '[]',
      allergies TEXT DEFAULT '[]',
      medicalHistory TEXT DEFAULT '[]',
      medicationHistory TEXT DEFAULT '[]',
      systemicDiseases TEXT DEFAULT '[]',
      source TEXT DEFAULT 'WALK_IN',
      familyId TEXT,
      referrer TEXT,
      emergencyContact TEXT,
      emergencyPhone TEXT,
      openId TEXT,
      clinicId TEXT NOT NULL,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code),
      FOREIGN KEY (familyId) REFERENCES Family(id),
      FOREIGN KEY (clinicId) REFERENCES Clinic(id)
    );
CREATE TABLE IF NOT EXISTS Family (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS FollowUp (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      planDate TEXT NOT NULL,
      content TEXT,
      type TEXT,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_ANSWER')),
      result TEXT,
      assigneeId TEXT,
      completedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (assigneeId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS FollowUpTemplate (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      type TEXT,
      daysAfter INTEGER DEFAULT 1,
      content TEXT,
      assigneeId TEXT,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS FollowUpItem (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      templateId TEXT,
      sortOrder INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS FollowUpResult (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT,
      sortOrder INTEGER DEFAULT 0,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS AutoFollowUpRule (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      triggerType TEXT,
      triggerDays INTEGER DEFAULT 1,
      templateId TEXT,
      assigneeId TEXT,
      isEnabled INTEGER DEFAULT 1,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (templateId) REFERENCES FollowUpTemplate(id)
    );
CREATE TABLE IF NOT EXISTS Registration (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      doctorId TEXT,
      type TEXT NOT NULL,
      status TEXT DEFAULT 'REGISTERED' CHECK (status IN ('REGISTERED', 'TRIAGED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
      visitId TEXT,
      appointmentId TEXT,
      triageNote TEXT,
      chiefComplaint TEXT,
      registeredBy TEXT,
      registeredAt TEXT DEFAULT CURRENT_TIMESTAMP,
      triagedAt TEXT,
      startedAt TEXT,
      completedAt TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (doctorId) REFERENCES User(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (appointmentId) REFERENCES Appointment(id)
    );
CREATE TABLE IF NOT EXISTS DrugCatalog (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      spec TEXT NOT NULL,
      category TEXT NOT NULL,
      price REAL NOT NULL CHECK (price >= 0),
      unit TEXT NOT NULL,
      stock REAL DEFAULT 0 CHECK (stock >= 0),
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, code)
    );
CREATE TABLE IF NOT EXISTS Prescription (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT NOT NULL,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS PrescriptionItem (
      id TEXT PRIMARY KEY,
      prescriptionId TEXT NOT NULL,
      drugCode TEXT,
      drugName TEXT NOT NULL,
      spec TEXT NOT NULL,
      dosage TEXT NOT NULL,
      frequency TEXT NOT NULL,
      days INTEGER NOT NULL CHECK (days >= 1),
      quantity REAL NOT NULL CHECK (quantity >= 0),
      unit TEXT NOT NULL,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (prescriptionId) REFERENCES Prescription(id) ON DELETE CASCADE
    );
CREATE TABLE IF NOT EXISTS Imaging (
      id TEXT PRIMARY KEY,
      patientId TEXT NOT NULL,
      visitId TEXT,
      doctorId TEXT,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT,
      imageUrl TEXT NOT NULL,
      thumbnailUrl TEXT,
      takenAt TEXT DEFAULT CURRENT_TIMESTAMP,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id),
      FOREIGN KEY (visitId) REFERENCES Visit(id),
      FOREIGN KEY (doctorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS DrugContraindication (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      drugAId TEXT,
      drugBId TEXT,
      drugCategoryA TEXT,
      drugCategoryB TEXT,
      severity TEXT NOT NULL CHECK(severity IN ('INFO','WARN','DANGER')) DEFAULT 'WARN',
      reason TEXT NOT NULL,
      pregnancyFlag INTEGER DEFAULT 0,
      lactationFlag INTEGER DEFAULT 0,
      renalFlag INTEGER DEFAULT 0,
      hepaticFlag INTEGER DEFAULT 0,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (drugAId) REFERENCES DrugCatalog(id),
      FOREIGN KEY (drugBId) REFERENCES DrugCatalog(id)
    );
CREATE TABLE IF NOT EXISTS Clinic (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code TEXT UNIQUE NOT NULL,
      address TEXT,
      phone TEXT,
      legalPerson TEXT,
      businessLicense TEXT,
      isActive INTEGER DEFAULT 1 CHECK (isActive IN (0,1)),
      remark TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    );
CREATE TABLE IF NOT EXISTS User (
      id TEXT PRIMARY KEY,
      username TEXT NOT NULL,
      passwordHash TEXT NOT NULL,
      name TEXT NOT NULL,
      role TEXT DEFAULT 'RECEPTIONIST' CHECK (role IN ('BOSS','DOCTOR','RECEPTIONIST','NURSE','ADMIN')),
      phone TEXT,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      loginAttempts INTEGER DEFAULT 0 CHECK (loginAttempts >= 0),
      lockedUntil TEXT,
      passwordNeedsRehash INTEGER DEFAULT 0,
      tokenVersion INTEGER DEFAULT 0,
      refreshToken TEXT,
      refreshTokenExpiresAt TEXT,
      passwordChangedAt TEXT,
      isTempPassword INTEGER DEFAULT 0 CHECK (isTempPassword IN (0,1)),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (clinicId) REFERENCES Clinic(id),
      UNIQUE(clinicId, username)
    );
CREATE TABLE IF NOT EXISTS UsedRefreshToken (
      tokenHash TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      usedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (userId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS ClinicInfo (
      id TEXT PRIMARY KEY,
      key TEXT NOT NULL,
      value TEXT,
      clinicId TEXT,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, key)
    );
CREATE TABLE IF NOT EXISTS OperationLog (
      id TEXT PRIMARY KEY,
      userId TEXT,
      userName TEXT,
      action TEXT NOT NULL,
      target TEXT,
      detail TEXT,
      ip TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS schema_migrations (
      version TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      appliedAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS AuditLog (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      targetId TEXT NOT NULL,
      targetType TEXT NOT NULL,
      operatorId TEXT,
      operatorName TEXT,
      amount REAL,
      beforeData TEXT,
      afterData TEXT,
      remark TEXT,
      ip TEXT,
      userAgent TEXT,
      source TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      prevHash TEXT,
      hash TEXT
    );
CREATE TABLE IF NOT EXISTS BackupRecord (
      id TEXT PRIMARY KEY,
      filename TEXT NOT NULL,
      fileSize INTEGER,
      type TEXT DEFAULT 'MANUAL',
      operatorId TEXT,
      operatorName TEXT,
      remark TEXT,
      clinicId TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (operatorId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS PrintTemplate (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL CHECK (category IN ('PRESCRIPTION','FINANCIAL','CLINICAL','REPORT')),
      content TEXT NOT NULL,
      variables TEXT NOT NULL DEFAULT '{}',
      isDefault INTEGER DEFAULT 0 CHECK (isDefault IN (0,1)),
      paperSize TEXT DEFAULT 'A4' CHECK (paperSize IN ('A4','A5','RECEIPT')),
      orientation TEXT DEFAULT 'portrait' CHECK (orientation IN ('portrait','landscape')),
      clinicId TEXT NOT NULL,
      createdBy TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code)
    );
CREATE TABLE IF NOT EXISTS IdempotencyRecord (
      id TEXT PRIMARY KEY,
      key TEXT UNIQUE NOT NULL,
      type TEXT NOT NULL,
      status TEXT DEFAULT 'PROCESSING',
      result TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      expiresAt TEXT NOT NULL
    );
CREATE TABLE IF NOT EXISTS SystemAlert (
      id TEXT PRIMARY KEY,
      level TEXT NOT NULL CHECK (level IN ('INFO','WARNING','ERROR','CRITICAL')),
      category TEXT NOT NULL,
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      data TEXT,
      resolved INTEGER DEFAULT 0 CHECK (resolved IN (0,1)),
      resolvedAt TEXT,
      consecutiveFailures INTEGER DEFAULT 0,
      clinicId TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE IF NOT EXISTS Notification (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      userId TEXT,
      type TEXT NOT NULL CHECK (type IN ('system','appointment','charge','inventory','patient','clinical','financial','equipment')),
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
      readAt TEXT,
      data TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (clinicId) REFERENCES Clinic(id),
      FOREIGN KEY (userId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS BusinessAlert (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      alertType TEXT NOT NULL CHECK(alertType IN ('REVENUE_DROP','NEW_PATIENTS','NO_SHOW_RATE','AOV','INVENTORY_STOCKOUT','SCHEDULER_TASK_FAILURE','PERFORMANCE_ANOMALY','SATISFACTION_NEGATIVE')),
      severity TEXT NOT NULL CHECK(severity IN ('INFO','WARN','CRITICAL')) DEFAULT 'WARN',
      metricName TEXT NOT NULL,
      currentValue REAL,
      baselineValue REAL,
      deviationPercent REAL,
      message TEXT NOT NULL,
      suggestion TEXT,
      acknowledged INTEGER DEFAULT 0 CHECK(acknowledged IN (0,1)),
      acknowledgedAt TEXT,
      acknowledgedBy TEXT,
      occurredAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (acknowledgedBy) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS StaffSchedule (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      staffId TEXT NOT NULL,
      scheduleDate TEXT NOT NULL,
      shiftId TEXT,
      startTime TEXT,
      endTime TEXT,
      station TEXT,
      remark TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, staffId, scheduleDate, shiftId),
      FOREIGN KEY (staffId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS StaffLeaveRequest (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      staffId TEXT NOT NULL,
      leaveType TEXT NOT NULL CHECK(leaveType IN ('ANNUAL','SICK','PERSONAL','MATERNITY','PATERNITY','OTHER')),
      startDate TEXT NOT NULL,
      endDate TEXT NOT NULL,
      daysCount REAL NOT NULL,
      reason TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('SAVED','PENDING','APPROVED','REJECTED','CANCELLED')) DEFAULT 'SAVED',
      approverId TEXT,
      approvedAt TEXT,
      rejectReason TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (staffId) REFERENCES User(id),
      FOREIGN KEY (approverId) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS DataImportJob (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      importType TEXT NOT NULL CHECK(importType IN ('PATIENT','DRUG_CATALOG','INVENTORY')),
      fileName TEXT NOT NULL,
      totalRows INTEGER DEFAULT 0,
      successRows INTEGER DEFAULT 0,
      failedRows INTEGER DEFAULT 0,
      errorReportPath TEXT,
      status TEXT NOT NULL CHECK(status IN ('UPLOADED','VALIDATING','VALIDATED','IMPORTING','COMPLETED','FAILED')) DEFAULT 'UPLOADED',
      startedById TEXT,
      completedAt TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (startedById) REFERENCES User(id)
    );
CREATE TABLE IF NOT EXISTS WechatMessage (
      id TEXT PRIMARY KEY,
      patientId TEXT,
      patientName TEXT,
      openId TEXT,
      content TEXT NOT NULL,
      type TEXT NOT NULL,
      templateId TEXT,
      status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
      sentAt TEXT,
      remark TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (patientId) REFERENCES Patient(id)
    );
