export const systemTables = [
  `CREATE TABLE IF NOT EXISTS Clinic (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code TEXT UNIQUE NOT NULL,
      address TEXT,
      phone TEXT,
      legalPerson TEXT,
      businessLicense TEXT,
      isActive INTEGER DEFAULT 1 CHECK (isActive IN (0,1)),
      remark TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS User (
      id TEXT PRIMARY KEY,
      username TEXT NOT NULL,
      passwordHash TEXT NOT NULL,
      name TEXT NOT NULL,
      role TEXT DEFAULT 'RECEPTIONIST' CHECK (role IN ('BOSS','DOCTOR','RECEPTIONIST','NURSE','ADMIN')),
      phone TEXT,
      active INTEGER DEFAULT 1 CHECK (active IN (0,1)),
      loginAttempts INTEGER DEFAULT 0 CHECK (loginAttempts >= 0),
      lockedUntil TEXT,
      passwordNeedsRehash INTEGER DEFAULT 0,
      tokenVersion INTEGER DEFAULT 0,
      refreshToken TEXT,
      refreshTokenExpiresAt TEXT,
      passwordChangedAt TEXT,
      isTempPassword INTEGER DEFAULT 0 CHECK (isTempPassword IN (0,1)),
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (clinicId) REFERENCES Clinic(id),
      UNIQUE(clinicId, username)
    )`,
  `CREATE TABLE IF NOT EXISTS UsedRefreshToken (
      tokenHash TEXT PRIMARY KEY,
      userId TEXT NOT NULL,
      usedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (userId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS ClinicInfo (
      id TEXT PRIMARY KEY,
      key TEXT NOT NULL,
      value TEXT,
      clinicId TEXT,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(clinicId, key)
    )`,
  `CREATE TABLE IF NOT EXISTS OperationLog (
      id TEXT PRIMARY KEY,
      userId TEXT,
      userName TEXT,
      action TEXT NOT NULL,
      target TEXT,
      detail TEXT,
      ip TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS schema_migrations (
      version TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      appliedAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS AuditLog (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      targetId TEXT NOT NULL,
      targetType TEXT NOT NULL,
      operatorId TEXT,
      operatorName TEXT,
      amount REAL,
      beforeData TEXT,
      afterData TEXT,
      remark TEXT,
      ip TEXT,
      userAgent TEXT,
      source TEXT,
      clinicId TEXT NOT NULL,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      prevHash TEXT,
      hash TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS BackupRecord (
      id TEXT PRIMARY KEY,
      filename TEXT NOT NULL,
      fileSize INTEGER,
      type TEXT DEFAULT 'MANUAL',
      operatorId TEXT,
      operatorName TEXT,
      remark TEXT,
      clinicId TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (operatorId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS PrintTemplate (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      category TEXT NOT NULL CHECK (category IN ('PRESCRIPTION','FINANCIAL','CLINICAL','REPORT')),
      content TEXT NOT NULL,
      variables TEXT NOT NULL DEFAULT '{}',
      isDefault INTEGER DEFAULT 0 CHECK (isDefault IN (0,1)),
      paperSize TEXT DEFAULT 'A4' CHECK (paperSize IN ('A4','A5','RECEIPT')),
      orientation TEXT DEFAULT 'portrait' CHECK (orientation IN ('portrait','landscape')),
      clinicId TEXT NOT NULL,
      createdBy TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, code)
    )`,
  `CREATE TABLE IF NOT EXISTS IdempotencyRecord (
      id TEXT PRIMARY KEY,
      key TEXT UNIQUE NOT NULL,
      type TEXT NOT NULL,
      status TEXT DEFAULT 'PROCESSING',
      result TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      expiresAt TEXT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS SystemAlert (
      id TEXT PRIMARY KEY,
      level TEXT NOT NULL CHECK (level IN ('INFO','WARNING','ERROR','CRITICAL')),
      category TEXT NOT NULL,
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      data TEXT,
      resolved INTEGER DEFAULT 0 CHECK (resolved IN (0,1)),
      resolvedAt TEXT,
      consecutiveFailures INTEGER DEFAULT 0,
      clinicId TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
    )`,
  `CREATE TABLE IF NOT EXISTS Notification (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      userId TEXT,
      type TEXT NOT NULL CHECK (type IN ('system','appointment','charge','inventory','patient','clinical','financial','equipment')),
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
      readAt TEXT,
      data TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (clinicId) REFERENCES Clinic(id),
      FOREIGN KEY (userId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS BusinessAlert (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      alertType TEXT NOT NULL CHECK(alertType IN ('REVENUE_DROP','NEW_PATIENTS','NO_SHOW_RATE','AOV','INVENTORY_STOCKOUT','SCHEDULER_TASK_FAILURE','PERFORMANCE_ANOMALY','SATISFACTION_NEGATIVE')),
      severity TEXT NOT NULL CHECK(severity IN ('INFO','WARN','CRITICAL')) DEFAULT 'WARN',
      metricName TEXT NOT NULL,
      currentValue REAL,
      baselineValue REAL,
      deviationPercent REAL,
      message TEXT NOT NULL,
      suggestion TEXT,
      acknowledged INTEGER DEFAULT 0 CHECK(acknowledged IN (0,1)),
      acknowledgedAt TEXT,
      acknowledgedBy TEXT,
      occurredAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (acknowledgedBy) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS StaffSchedule (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      staffId TEXT NOT NULL,
      scheduleDate TEXT NOT NULL,
      shiftId TEXT,
      startTime TEXT,
      endTime TEXT,
      station TEXT,
      remark TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      UNIQUE(clinicId, staffId, scheduleDate, shiftId),
      FOREIGN KEY (staffId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS StaffLeaveRequest (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      staffId TEXT NOT NULL,
      leaveType TEXT NOT NULL CHECK(leaveType IN ('ANNUAL','SICK','PERSONAL','MATERNITY','PATERNITY','OTHER')),
      startDate TEXT NOT NULL,
      endDate TEXT NOT NULL,
      daysCount REAL NOT NULL,
      reason TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('SAVED','PENDING','APPROVED','REJECTED','CANCELLED')) DEFAULT 'SAVED',
      approverId TEXT,
      approvedAt TEXT,
      rejectReason TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (staffId) REFERENCES User(id),
      FOREIGN KEY (approverId) REFERENCES User(id)
    )`,
  `CREATE TABLE IF NOT EXISTS DataImportJob (
      id TEXT PRIMARY KEY,
      clinicId TEXT NOT NULL,
      importType TEXT NOT NULL CHECK(importType IN ('PATIENT','DRUG_CATALOG','INVENTORY')),
      fileName TEXT NOT NULL,
      totalRows INTEGER DEFAULT 0,
      successRows INTEGER DEFAULT 0,
      failedRows INTEGER DEFAULT 0,
      errorReportPath TEXT,
      status TEXT NOT NULL CHECK(status IN ('UPLOADED','VALIDATING','VALIDATED','IMPORTING','COMPLETED','FAILED')) DEFAULT 'UPLOADED',
      startedById TEXT,
      completedAt TEXT,
      createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
      updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
      deletedAt TEXT,
      FOREIGN KEY (startedById) REFERENCES User(id)
    )`,
];
