export * from './prescriptions/prescriptions.module';
export * from './prescriptions/prescriptions.service';
export * from './prescriptions/prescriptions.controller';
export * from './imaging/imaging.module';
export * from './imaging/imaging.service';
export * from './imaging/imaging.controller';
export * from './tooth-records/tooth-records.module';
export * from './tooth-records/tooth-records.service';
export * from './tooth-records/tooth-records.controller';
