export enum ErrorCode {
  UNKNOWN = 1000,
  BAD_REQUEST = 1001,
  UNAUTHORIZED = 1002,
  FORBIDDEN = 1003,
  NOT_FOUND = 1004,
  CONFLICT = 1005,
  VALIDATION_ERROR = 1006,

  INVALID_CREDENTIALS = 2001,
  TOKEN_EXPIRED = 2002,
  TOKEN_INVALID = 2003,
  TOO_MANY_ATTEMPTS = 2004,
  ACCOUNT_LOCKED = 2005,

  INSUFFICIENT_BALANCE = 3001,
  INVALID_STATUS_TRANSITION = 3002,
  DUPLICATE_ENTRY = 3003,
  RESOURCE_OWNERSHIP_VIOLATION = 3004,

  DATA_INTEGRITY_ERROR = 4001,
  REFERENCE_NOT_FOUND = 4002,
}

export const errorMessages: Record<ErrorCode, string> = {
  [ErrorCode.UNKNOWN]: '服务器内部错误',
  [ErrorCode.BAD_REQUEST]: '请求参数错误',
  [ErrorCode.UNAUTHORIZED]: '未授权访问',
  [ErrorCode.FORBIDDEN]: '权限不足',
  [ErrorCode.NOT_FOUND]: '资源不存在',
  [ErrorCode.CONFLICT]: '资源冲突',
  [ErrorCode.VALIDATION_ERROR]: '参数校验失败',

  [ErrorCode.INVALID_CREDENTIALS]: '用户名或密码错误',
  [ErrorCode.TOKEN_EXPIRED]: '令牌已过期',
  [ErrorCode.TOKEN_INVALID]: '令牌无效',
  [ErrorCode.TOO_MANY_ATTEMPTS]: '尝试次数过多',
  [ErrorCode.ACCOUNT_LOCKED]: '账户已锁定',

  [ErrorCode.INSUFFICIENT_BALANCE]: '余额不足',
  [ErrorCode.INVALID_STATUS_TRANSITION]: '无效的状态转换',
  [ErrorCode.DUPLICATE_ENTRY]: '重复条目',
  [ErrorCode.RESOURCE_OWNERSHIP_VIOLATION]: '资源所有权违规',

  [ErrorCode.DATA_INTEGRITY_ERROR]: '数据完整性错误',
  [ErrorCode.REFERENCE_NOT_FOUND]: '引用不存在',
};

export enum LegacyErrorCode {
  AUTH_UNAUTHORIZED = 'AUTH_001',
  AUTH_TOKEN_EXPIRED = 'AUTH_002',
  AUTH_TOKEN_INVALID = 'AUTH_003',
  AUTH_LOGIN_FAILED = 'AUTH_004',
  AUTH_PASSWORD_INCORRECT = 'AUTH_005',
  AUTH_ACCOUNT_DISABLED = 'AUTH_006',
  AUTH_ACCOUNT_LOCKED = 'AUTH_007',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_008',

  VALIDATION_ERROR = 'GEN_001',
  VALIDATION_MISSING_FIELD = 'GEN_002',
  VALIDATION_INVALID_FORMAT = 'GEN_003',

  NOT_FOUND = 'GEN_004',
  NOT_FOUND_USER = 'GEN_005',
  NOT_FOUND_PATIENT = 'GEN_006',
  NOT_FOUND_RESOURCE = 'GEN_007',

  CONFLICT = 'GEN_008',
  CONFLICT_UNIQUE_CONSTRAINT = 'GEN_009',
  CONFLICT_DUPLICATE = 'GEN_010',
  DUPLICATE_ENTRY = 'GEN_011',

  PATIENT_NOT_FOUND = 'PATIENT_001',
  PATIENT_DUPLICATE = 'PATIENT_002',

  CHARGE_NOT_FOUND = 'CHARGE_001',
  CHARGE_ALREADY_PAID = 'CHARGE_002',
  CHARGE_CANCELLED = 'CHARGE_003',
  PAYMENT_FAILED = 'CHARGE_004',

  INSUFFICIENT_STOCK = 'INVENTORY_001',
  ITEM_NOT_FOUND = 'INVENTORY_002',

  CARD_NOT_FOUND = 'CARD_001',
  CARD_INSUFFICIENT_BALANCE = 'CARD_002',
  CARD_DISABLED = 'CARD_003',

  REFUND_EXCEEDS_PAID = 'REFUND_001',
  REFUND_ALREADY_PROCESSED = 'REFUND_002',

  BUSINESS_ERROR = 'BIZ_001',
  BUSINESS_OPERATION_FAILED = 'BIZ_002',
  BUSINESS_BACKUP_FAILED = 'BIZ_003',
  BUSINESS_RESTORE_FAILED = 'BIZ_004',
  BUSINESS_CONFIG_ERROR = 'BIZ_005',
  BUSINESS_DATABASE_ERROR = 'BIZ_006',

  INTERNAL_ERROR = 'GEN_012',

  DB_ERROR = 'DB_001',
  DB_FOREIGN_KEY_CONSTRAINT = 'DB_002',
  DB_CHECK_CONSTRAINT = 'DB_003',
  DB_NOT_NULL_CONSTRAINT = 'DB_004',
  DB_BUSY_TIMEOUT = 'DB_005',
  DB_LOCKED = 'DB_006',
  DB_CORRUPT = 'DB_007',
  DB_READONLY = 'DB_008',
  DB_IO_ERROR = 'DB_009',

  PAYLOAD_TOO_LARGE = 'REQ_001',
  BAD_REQUEST_LEGACY = 'REQ_002',
  UNSUPPORTED_MEDIA_TYPE = 'REQ_003',

  RATE_LIMITED = 'RATE_001',
}
