import type { ResourceDefinition } from '../contracts';
import { f, crud, boss, clinical } from './shared';

/** clinicalResources：8 个资源定义（见原 resources.ts 分组） */
export const clinicalResources: ResourceDefinition[] = [
  crud('medicalRecords', 'MedicalRecord', [
    f('patientId', 'relation', { required: true, relation: { resource: 'patients', foreignKey: 'patientId', labelField: 'name' } }),
    f('visitId', 'relation', { relation: { resource: 'visits', foreignKey: 'visitId', labelField: 'id' } }),
    f('doctorId', 'relation', { relation: { resource: 'users', foreignKey: 'doctorId', labelField: 'name' } }),
    f('templateId', 'text'),
    f('isTemplate', 'boolean', { default: false }),
    f('category', 'text'),
    f('chiefComplaint', 'longText'),
    f('presentIllness', 'longText'),
    f('pastHistory', 'longText'),
    f('allergyHistory', 'longText'),
    f('examination', 'longText'),
    f('diagnosis', 'longText'),
    f('treatmentPlan', 'longText'),
    f('teethInvolved', 'json', { default: '[]' }),
    f('images', 'json', { default: '[]' }),
    f('isLocked', 'boolean', { default: false }),
    f('lockedAt', 'datetime'),
    f('lockedBy', 'text'),
    f('signature', 'text'),
    f('status', 'text', { required: true }),
    f('editRequestStatus', 'enum', { enumValues: ['NONE', 'PENDING', 'APPROVED', 'REJECTED'] }),
    f('editRequestReason', 'longText'),
    f('editRequestedById', 'text'),
    f('editRequestedAt', 'datetime'),
    f('reviewedById', 'text'),
    f('reviewedAt', 'datetime'),
    f('reviewNote', 'longText'),
    f('proposedContentJson', 'longText'),
  ], { roles: clinical, capabilities: { list: true, create: true, update: true, delete: true, softDelete: true } }),

  crud('medicalPhrases', 'MedicalPhrase', [
    f('category', 'text', { required: true }),
    f('content', 'longText', { required: true, searchable: true }),
    f('sortOrder', 'number', { default: 0 }),
  ], { roles: clinical }),

  crud('toothRecords', 'ToothRecord', [
    f('patientId', 'relation', { required: true, relation: { resource: 'patients', foreignKey: 'patientId', labelField: 'name' } }),
    f('toothNumber', 'number', { required: true }),
    f('currentStatus', 'text', { required: true }),
    f('conditions', 'json', { default: '[]' }),
    f('remark', 'longText'),
  ], { roles: clinical, capabilities: { list: true, create: true, update: false, delete: false, softDelete: false } }),

  crud('imaging', 'Imaging', [
    f('patientId', 'relation', { required: true, relation: { resource: 'patients', foreignKey: 'patientId', labelField: 'name' } }),
    f('visitId', 'relation', { relation: { resource: 'visits', foreignKey: 'visitId', labelField: 'id' } }),
    f('doctorId', 'relation', { relation: { resource: 'users', foreignKey: 'doctorId', labelField: 'name' } }),
    f('type', 'text', { required: true, searchable: true }),
    f('title', 'text', { required: true, searchable: true }),
    f('description', 'longText'),
    f('imageUrl', 'text', { required: true }),
    f('thumbnailUrl', 'text'),
    f('takenAt', 'datetime'),
    f('remark', 'longText'),
    f('categoryId', 'text'),
    f('phase', 'enum', { enumValues: ['INITIAL', 'IN_PROGRESS', 'FINISHED', 'RETENTION', 'OTHER'] }),
  ], { roles: clinical, capabilities: { list: true, create: true, update: true, delete: true, softDelete: true } }),

  crud('treatmentCatalogs', 'TreatmentCatalog', [
    f('code', 'text', { required: true, unique: true, searchable: true }),
    f('name', 'text', { required: true, searchable: true }),
    f('category', 'text', { required: true }),
    f('price', 'money', { required: true }),
    f('remark', 'longText'),
    f('costType', 'enum', { enumValues: ['SERVICE', 'MATERIAL'] }),
    f('anesthesia', 'boolean', { default: false }),
    f('parentId', 'text'),
    f('businessCategory', 'enum', { enumValues: ['SERVICE', 'DRUG', 'MATERIAL', 'OTHER'] }),
  ], { roles: boss }),

  crud('treatments', 'Treatment', [
    f('patientId', 'relation', { required: true, relation: { resource: 'patients', foreignKey: 'patientId', labelField: 'name' } }),
    f('visitId', 'relation', { relation: { resource: 'visits', foreignKey: 'visitId', labelField: 'id' } }),
    f('doctorId', 'relation', { required: true, relation: { resource: 'users', foreignKey: 'doctorId', labelField: 'name' } }),
    f('code', 'text', { required: true }),
    f('name', 'text', { required: true, searchable: true }),
    f('category', 'text', { required: true }),
    f('price', 'money', { required: true }),
    f('quantity', 'number', { required: true, min: 1 }),
    f('teethNumbers', 'json', { default: '[]' }),
    f('status', 'enum', { required: true, enumValues: ['PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'] }),
    f('plannedDate', 'date'),
    f('completedDate', 'date'),
    f('remark', 'longText'),
  ], { roles: clinical, capabilities: { list: true, create: true, update: true, delete: true, softDelete: true } }),

  // R2-P1-19: 允许软删除（无级联），供创建失败时客户端清理孤儿主记录/明细
  crud('treatmentPlans', 'TreatmentPlan', [
    f('patientId', 'relation', { required: true, relation: { resource: 'patients', foreignKey: 'patientId', labelField: 'name' } }),
    f('visitId', 'relation', { relation: { resource: 'visits', foreignKey: 'visitId', labelField: 'id' } }),
    f('doctorId', 'relation', { required: true, relation: { resource: 'users', foreignKey: 'doctorId', labelField: 'name' } }),
    f('name', 'text', { required: true, searchable: true }),
    f('status', 'text', { required: true }),
    f('totalFee', 'money', { required: true }),
    f('remark', 'longText'),
    f('printCount', 'number', { default: 0 }),
    f('lastPrintedAt', 'datetime'),
    f('patientSignature', 'text'),
    f('signedAt', 'datetime'),
    f('signerName', 'text'),
    f('signatureRemark', 'longText'),
    f('discountType', 'enum', { enumValues: ['NONE', 'WHOLE', 'DOUBLE'] }),
    f('discountRate', 'number', { min: 0, max: 100 }),
    f('followUpStatus', 'enum', { enumValues: ['NONE', 'PENDING', 'HORIZONTAL_SHOULD', 'HORIZONTAL_DONE', 'LOST'] }),
    f('nextFollowUpAt', 'date'),
    f('trackingNote', 'longText'),
  ], { roles: clinical, capabilities: { list: true, create: true, update: true, delete: true, softDelete: true } }),

  // R2-P1-19: 允许软删除（无级联），供创建失败时客户端清理孤儿主记录/明细
  crud('treatmentPlanItems', 'TreatmentPlanItem', [
    f('planId', 'relation', { required: true, relation: { resource: 'treatmentPlans', foreignKey: 'planId', labelField: 'name' } }),
    f('code', 'text', { required: true }),
    f('name', 'text', { required: true, searchable: true }),
    f('category', 'text', { required: true }),
    f('price', 'money', { required: true }),
    f('quantity', 'number', { required: true, min: 1 }),
    f('teethNumbers', 'json', { default: '[]' }),
    f('status', 'text', { required: true }),
    f('treatmentId', 'text'),
    f('completedAt', 'datetime'),
    f('remark', 'longText'),
    f('discountRate', 'number', { min: 0, max: 100 }),
    f('billed', 'boolean', { default: false }),
    f('billedChargeId', 'text'),
  ], { roles: clinical, capabilities: { list: true, create: true, update: true, delete: true, softDelete: true } }),

];
