import { addColumnIfMissing, logger, tableExists } from './helpers';

export const migrateToV32 = () => {
  if (tableExists('Visit')) {
    addColumnIfMissing('Visit', 'nextReminder', 'TEXT');
    addColumnIfMissing('Visit', 'summaryAutoGenerated', "INTEGER DEFAULT 0 CHECK(summaryAutoGenerated IN (0,1))");
    logger.log('v32: Visit 表已添加 nextReminder 和 summaryAutoGenerated 列');
  } else {
    logger.log('v32: Visit 表不存在，跳过 Visit 加列');
  }

  if (tableExists('MedicalRecordPhrase')) {
    addColumnIfMissing('MedicalRecordPhrase', 'ownerId', 'TEXT');
    addColumnIfMissing('MedicalRecordPhrase', 'pinOrder', 'INTEGER DEFAULT 0');
    logger.log('v32: MedicalRecordPhrase 表已添加 ownerId 和 pinOrder 列');
  } else {
    logger.log('v32: MedicalRecordPhrase 表不存在，跳过 MedicalRecordPhrase 加列');
  }
};
