const tseslint = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');
const eslint = require('@eslint/js');
const globals = require('globals');
const sonarjs = require('eslint-plugin-sonarjs');
const unicorn = require('eslint-plugin-unicorn').default;
const security = require('eslint-plugin-security');
const n = require('eslint-plugin-n');
const prettier = require('eslint-config-prettier');

const baseRules = {
  ...eslint.configs.recommended.rules,
  ...tseslint.configs.recommended.rules,
  ...sonarjs.configs.recommended.rules,
  ...unicorn.configs['flat/recommended'].rules,
  ...n.configs['flat/recommended'].rules,
  ...security.configs.recommended.rules,
  ...prettier.rules,

  'no-console': 'off',

  // 允许下划线前缀的未使用变量（如 _isTestMode 表示"故意未使用"）
  '@typescript-eslint/no-unused-vars': [
    'warn',
    {
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_',
      destructuredArrayIgnorePattern: '^_',
      ignoreRestSiblings: true,
    },
  ],
  // TODO: 启用 strictNullChecks 后重新开启以下规则
  '@typescript-eslint/prefer-nullish-coalescing': 'off',
  '@typescript-eslint/no-unnecessary-condition': 'off',
  // no-explicit-any 已启用为 error，与 .qoder/rules/no-typescript-any.md 保持一致
  // 测试文件通过下方 overrides 豁免（规则允许测试中使用 as any 进行 mock）
  // no-unsafe-* 规则需要 strictNullChecks 启用后才能正确工作
  '@typescript-eslint/no-unsafe-assignment': 'off',
  '@typescript-eslint/no-unsafe-member-access': 'off',
  '@typescript-eslint/no-unsafe-argument': 'off',
  '@typescript-eslint/no-require-imports': 'off',
  '@typescript-eslint/no-empty-function': 'off',
  '@typescript-eslint/no-empty-object-type': 'off',
  '@typescript-eslint/ban-ts-comment': 'off',
  '@typescript-eslint/no-namespace': 'off',
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/no-dynamic-delete': 'off',
  '@typescript-eslint/no-extraneous-class': 'off',
  '@typescript-eslint/no-inferrable-types': 'off',
  '@typescript-eslint/prefer-for-of': 'off',
  '@typescript-eslint/prefer-includes': 'warn',
  '@typescript-eslint/prefer-optional-chain': 'off',
  '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
  '@typescript-eslint/prefer-function-type': 'off',
  '@typescript-eslint/unified-signatures': 'off',
  '@typescript-eslint/no-this-alias': 'off',
  'no-undef': 'off',
  'no-empty': 'warn',
  'no-redeclare': 'warn',
  'no-useless-escape': 'warn',
  'no-useless-assignment': 'warn',
  'prefer-arrow-callback': 'warn',
  'no-var': 'warn',
  'object-shorthand': 'warn',

  'sonarjs/no-duplicate-string': 'off',
  'sonarjs/no-collection-size-mischeck': 'warn',
  'sonarjs/cognitive-complexity': 'off',
  'sonarjs/no-big-function': 'off',
  'sonarjs/no-commented-code': 'off',
  'sonarjs/no-magic-numbers': 'off',
  'sonarjs/no-parameter-reassignment': 'off',
  'sonarjs/prefer-immediate-return': 'off',
  'sonarjs/prefer-optional': 'off',
  'sonarjs/prefer-readonly': 'off',
  'sonarjs/no-nested-conditional': 'off',
  'sonarjs/no-confusing-enum': 'off',
  'sonarjs/no-file-name-differ-from-class': 'off',
  'sonarjs/no-identical-functions': 'warn',
  'sonarjs/no-single-alternative-iteration': 'off',
  'sonarjs/no-single-switch-case': 'off',
  'sonarjs/no-useless-increment': 'off',
  'sonarjs/prefer-promise-shorthand': 'off',
  'sonarjs/parameters-max-number': 'off',
  'sonarjs/prefer-default-last': 'off',
  'sonarjs/null-dereference': 'off',
  'sonarjs/argument-type': 'off',
  'sonarjs/no-unused-vars': 'off',
  'sonarjs/no-dead-store': 'off',
  'sonarjs/unused-import': 'off',
  'sonarjs/prefer-specific-assertions': 'off',
  'sonarjs/parameterized-tests': 'off',
  'sonarjs/function-return-type': 'off',
  'sonarjs/use-type-alias': 'off',
  'sonarjs/no-inverted-boolean-check': 'off',
  'sonarjs/no-redundant-jump': 'off',
  'sonarjs/prefer-includes': 'off',
  'sonarjs/prefer-regexp-test': 'off',
  'sonarjs/concise-regex': 'off',
  'sonarjs/no-empty-test-file': 'off',
  'sonarjs/no-empty-test-suite': 'off',
  'sonarjs/no-exclusive-tests': 'off',
  'sonarjs/no-skipped-tests': 'off',
  'sonarjs/no-incomplete-assertions': 'off',
  'sonarjs/todo-tag': 'off',
  'sonarjs/no-slow-regex': 'off',
  'sonarjs/no-useless-intersection': 'off',
  'sonarjs/no-useless-mapped-types': 'off',
  'sonarjs/no-import-type-side-effects': 'off',
  'sonarjs/no-inconsistent-function-declaration': 'off',
  'sonarjs/duplicates-in-character-class': 'off',
  'sonarjs/no-superfluous-else': 'off',
  'sonarjs/no-redundant-boolean': 'off',
  'sonarjs/no-useless-catch': 'off',
  'sonarjs/no-useless-promise-resolve-reject': 'off',
  'sonarjs/use-isnan': 'off',
  'sonarjs/no-array-constructor': 'off',
  'sonarjs/no-empty-collection': 'off',
  'sonarjs/no-empty-destructuring': 'off',
  'sonarjs/no-empty-pattern': 'off',
  'sonarjs/no-nested-switch': 'off',
  'sonarjs/pseudo-random': 'warn',

  'security/detect-child-process': 'warn',
  'security/detect-non-literal-fs-filename': 'warn',
  'security/detect-non-literal-regexp': 'off',
  'security/detect-non-literal-require': 'warn',
  'security/detect-eval-with-expression': 'warn',
  'security/detect-pseudoRandomBytes': 'off',
  'security/detect-new-buffer': 'off',
  'security/detect-possible-timing-attacks': 'off',
  'security/detect-unsafe-regex': 'off',
  'security/detect-buffer-noassert': 'off',
  'security/detect-multi-statement': 'off',
  'security/detect-object-injection': 'off',
  'security/detect-handler': 'off',
  'security/detect-import-exports': 'off',
  'security/detect-template-literal-injections': 'off',
  'security/detect-disable-mustache-escape': 'off',
  'security/detect-no-csrf-before-method-override': 'off',

  'n/no-missing-import': 'off',
  'n/no-unpublished-import': 'off',
  'n/no-unpublished-require': 'off',
  'n/no-missing-require': 'off',
  'n/no-extraneous-import': 'off',
  'n/no-extraneous-require': 'off',
  'n/no-unsupported-features/es-syntax': 'off',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'n/exports-style': 'off',
  'n/file-extension-in-import': 'off',
  'n/global-require': 'off',
  'n/hashbang': 'off',
  'n/no-callback-literal': 'off',
  'n/no-deprecated-api': 'off',
  'n/no-exports-assign': 'off',
  'n/no-mixed-requires': 'off',
  'n/no-new-require': 'off',
  'n/no-path-concat': 'off',
  'n/no-process-env': 'off',
  'n/no-process-exit': 'off',
  'n/no-restricted-import': 'off',
  'n/no-restricted-require': 'off',
  'n/no-sync': 'off',
  'n/prefer-global/buffer': 'off',
  'n/prefer-global/console': 'off',
  'n/prefer-global/process': 'off',
  'n/prefer-global/text-decoder': 'off',
  'n/prefer-global/text-encoder': 'off',
  'n/prefer-global/url-search-params': 'off',
  'n/prefer-global/url': 'off',
  'n/prefer-node-protocol': 'off',
  'n/prefer-promises/dns': 'off',
  'n/prefer-promises/fs': 'off',

  'unicorn/prefer-module': 'off',
  'unicorn/prefer-top-level-await': 'off',
  'unicorn/no-null': 'off',
  'unicorn/prevent-abbreviations': 'off',
  'unicorn/filename-case': 'off',
  'unicorn/no-array-for-each': 'off',
  'unicorn/no-array-callback-reference': 'off',
  'unicorn/no-array-reduce': 'off',
  'unicorn/prefer-number-properties': 'off',
  'unicorn/prefer-set-has': 'off',
  'unicorn/prefer-spread': 'off',
  'unicorn/consistent-function-scoping': 'off',
  'unicorn/catch-error-name': 'off',
  'unicorn/import-style': 'off',
  'unicorn/no-anonymous-default-export': 'off',
  'unicorn/no-empty-file': 'warn',
  'unicorn/no-lonely-if': 'off',
  'unicorn/no-negated-condition': 'off',
  'unicorn/no-nested-ternary': 'off',
  'unicorn/no-useless-undefined': 'warn',
  'unicorn/prefer-query-selector': 'off',
  'unicorn/prefer-regexp-test': 'off',
  'unicorn/text-encoding-identifier-case': 'off',
  'unicorn/prefer-code-point': 'off',
  'unicorn/prefer-at': 'off',
  'unicorn/prefer-includes': 'warn',
  'unicorn/prefer-object-from-entries': 'off',
  'unicorn/prefer-optional-catch-binding': 'warn',
  'unicorn/relative-url-style': 'off',
  'unicorn/switch-case-braces': 'off',
  'unicorn/template-indent': 'off',
  'unicorn/numeric-separators-style': 'off',
  'unicorn/expiring-todo-comments': 'off',
  'unicorn/error-message': 'off',
  'unicorn/escape-case': 'off',
  'unicorn/new-for-builtins': 'off',
  'unicorn/no-array-push-push': 'off',
  'unicorn/no-await-expression-member': 'off',
  'unicorn/no-console-spaces': 'off',
  'unicorn/no-for-loop': 'off',
  'unicorn/no-hex-escape': 'off',
  'unicorn/no-instanceof-array': 'warn',
  'unicorn/no-new-array': 'off',
  'unicorn/no-new-buffer': 'off',
  'unicorn/no-object-as-default-parameter': 'off',
  'unicorn/no-process-exit': 'off',
  'unicorn/no-static-only-class': 'off',
  'unicorn/no-thenable': 'off',
  'unicorn/no-this-assignment': 'off',
  'unicorn/no-unreadable-array-destructuring': 'off',
  'unicorn/no-unreadable-iife': 'off',
  'unicorn/no-unsafe-regex': 'off',
  'unicorn/no-unused-properties': 'off',
  'unicorn/no-useless-fallback-in-spread': 'off',
  'unicorn/no-useless-length-check': 'off',
  'unicorn/no-useless-promise-resolve-reject': 'off',
  'unicorn/no-useless-spread': 'off',
  'unicorn/no-useless-switch-case': 'off',
  'unicorn/prefer-array-find': 'off',
  'unicorn/prefer-array-flat-map': 'off',
  'unicorn/prefer-array-index-of': 'off',
  'unicorn/prefer-array-some': 'off',
  'unicorn/prefer-date-now': 'off',
  'unicorn/prefer-default-parameters': 'off',
  'unicorn/prefer-dom-node-append': 'off',
  'unicorn/prefer-dom-node-dataset': 'off',
  'unicorn/prefer-dom-node-remove': 'off',
  'unicorn/prefer-dom-node-text-content': 'off',
  'unicorn/prefer-event-target': 'off',
  'unicorn/prefer-export-from': 'off',
  'unicorn/prefer-keyboard-event-key': 'off',
  'unicorn/prefer-math-trunc': 'off',
  'unicorn/prefer-modern-dom-apis': 'off',
  'unicorn/prefer-modern-math-apis': 'off',
  'unicorn/prefer-native-coercion-functions': 'off',
  'unicorn/prefer-negative-index': 'warn',
  'unicorn/prefer-node-protocol': 'warn',
  'unicorn/prefer-object-has-own': 'off',
  'unicorn/prefer-reflect-apply': 'off',
  'unicorn/prefer-string-replace-all': 'off',
  'unicorn/prefer-string-slice': 'off',
  'unicorn/prefer-string-starts-ends-with': 'warn',
  'unicorn/prefer-string-trim-start-end': 'off',
  'unicorn/prefer-switch': 'off',
  'unicorn/prefer-ternary': 'off',
  'unicorn/prefer-type-error': 'off',
  'unicorn/require-array-join-separator': 'off',
  'unicorn/require-number-to-fixed-digits-argument': 'off',
  'unicorn/require-post-message-target-origin': 'off',
  'unicorn/string-content': 'off',
  'unicorn/better-regex': 'off',
  'unicorn/consistent-destructuring': 'off',
  'unicorn/empty-brace-spaces': 'off',
  'unicorn/explicit-length-check': 'off',
  'unicorn/import-index': 'off',
  'unicorn/no-abusive-eslint-disable': 'off',
  'unicorn/no-array-method-this-argument': 'off',
  'unicorn/no-assignment-expression': 'off',
  'unicorn/no-callback-in-promise': 'off',
  'unicorn/no-document-cookie': 'off',
  'unicorn/no-empty-array-callback': 'off',
  'unicorn/no-eval': 'off',
  'unicorn/no-fn-reference-in-iterator': 'off',
  'unicorn/no-import-assign': 'off',
  'unicorn/no-invalid-remove-event-listener': 'off',
  'unicorn/no-keyword-prefix': 'off',
  'unicorn/no-magic-array-flat-depth': 'off',
  'unicorn/no-negation-in-equality-check': 'off',
  'unicorn/no-promise-executor-return': 'off',
  'unicorn/no-single-promise-in-promise-methods': 'off',
  'unicorn/no-typeof-undefined': 'off',
  'unicorn/no-unnecessary-await': 'off',
  'unicorn/no-unnecessary-polyfills': 'off',
  'unicorn/no-zero-fractions': 'off',
  'unicorn/prefer-add-event-listener': 'off',
  'unicorn/prefer-array-flat': 'off',
  'unicorn/prefer-blob-reading-methods': 'off',
  'unicorn/prefer-prototype-methods': 'off',
  'unicorn/prefer-text-content': 'off',
  'unicorn/prefer-set-size': 'off',
  'unicorn/throw-new-error': 'off',
  'unicorn/name-replacements': 'off',
  'unicorn/prefer-await': 'off',
  'unicorn/consistent-class-member-order': 'off',
  'unicorn/consistent-boolean-name': 'off',
  'unicorn/consistent-compound-words': 'off',
  'unicorn/max-nested-calls': 'off',
  'unicorn/no-useless-override': 'off',
  'unicorn/prefer-string-raw': 'off',
  'unicorn/no-for-each': 'off',
  'unicorn/prefer-continue': 'off',
  'unicorn/prefer-early-return': 'off',
  'unicorn/prefer-simple-condition-first': 'off',
  'unicorn/prefer-queue-microtask': 'off',
  'unicorn/no-array-sort': 'off',
  'unicorn/prefer-split-limit': 'off',
  'unicorn/no-non-function-verb-prefix': 'off',
  'unicorn/no-declarations-before-early-exit': 'off',
  'unicorn/prefer-number-coercion': 'off',
  'unicorn/no-useless-coercion': 'off',
  'unicorn/no-nonstandard-builtin-properties': 'off',
  'unicorn/prefer-includes-over-repeated-comparisons': 'off',
  'unicorn/prefer-array-from-map': 'off',
  'unicorn/no-break-in-nested-loop': 'off',
  'unicorn/no-top-level-assignment-in-function': 'off',
  'unicorn/class-reference-in-static-methods': 'off',
  'unicorn/prefer-direct-iteration': 'off',
  'unicorn/no-unnecessary-boolean-comparison': 'off',
  'unicorn/no-unnecessary-nested-ternary': 'off',
  'unicorn/no-useless-continue': 'off',
  'unicorn/prefer-single-call': 'off',
  'unicorn/no-negated-array-predicate': 'off',
  'unicorn/prefer-object-iterable-methods': 'off',
  'unicorn/no-useless-else': 'off',
  'unicorn/prefer-string-repeat': 'off',
  'unicorn/prefer-else-if': 'off',
  'unicorn/no-unnecessary-splice': 'off',
  'unicorn/no-unnecessary-array-splice-count': 'off',
  'unicorn/no-useless-error-capture-stack-trace': 'off',
  'unicorn/prefer-https': 'off',
  'no-import-assign': 'off',
  'sonarjs/sql-queries': 'off',

  // 架构约束：禁止 ORM 框架导入（项目使用原生 SQL + better-sqlite3）
  'no-restricted-imports': [
    'error',
    {
      patterns: [
        {
          group: ['prisma', '@prisma/*', 'prisma/*'],
          message: '禁止使用 Prisma ORM。本项目使用原生 SQL + better-sqlite3，参见 .qoder/rules/no-orm-usage.md',
        },
        {
          group: ['typeorm', 'typeorm/*'],
          message: '禁止使用 TypeORM。本项目使用原生 SQL + better-sqlite3，参见 .qoder/rules/no-orm-usage.md',
        },
        {
          group: ['sequelize', 'sequelize/*'],
          message: '禁止使用 Sequelize。本项目使用原生 SQL + better-sqlite3，参见 .qoder/rules/no-orm-usage.md',
        },
      ],
    },
  ],
};

module.exports = [
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        sourceType: 'module',
        ecmaVersion: 2022,
        project: './tsconfig.json',
      },
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      sonarjs,
      unicorn,
      security,
      n,
    },
    rules: baseRules,
  },
  {
    files: ['test/**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        sourceType: 'module',
        ecmaVersion: 2022,
      },
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      sonarjs,
      unicorn,
      security,
      n,
    },
    rules: baseRules,
  },
  // 测试与种子数据生成：合理使用 Math.random() 生成测试数据，非安全敏感场景
  // 测试文件豁免 no-explicit-any（.qoder/rules/no-typescript-any.md 允许测试中使用 as any 进行 mock）
  {
    files: [
      'test/**/*.ts',
    ],
    rules: {
      'sonarjs/pseudo-random': 'off',
      'no-empty': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/prefer-includes': 'off',
      'sonarjs/assertions-in-tests': 'off',
      'sonarjs/no-trivial-assertions': 'off',
      'sonarjs/no-hardcoded-passwords': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'unicorn/prefer-node-protocol': 'off',
    },
  },
  {
    files: [
      '**/*.spec.ts',
      '**/*.concurrent.spec.ts',
      '**/*.fault.spec.ts',
      '**/*.e2e-spec.ts',
      '**/*.smoke.spec.ts',
      '**/*.integration.spec.ts',
      'src/db/seed/**/*.ts',
      'src/common/test-helpers/**/*.ts',
    ],
    rules: {
      'sonarjs/pseudo-random': 'off',
      'no-empty': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      'sonarjs/super-linear-regex': 'off',
      'sonarjs/assertions-in-tests': 'off',
      'sonarjs/no-trivial-assertions': 'off',
      'sonarjs/no-hardcoded-passwords': 'off',
      'sonarjs/no-duplicated-branches': 'off',
      'unicorn/no-duplicate-if-branches': 'off',
    },
  },
  {
    ignores: ['dist', 'node_modules', 'bundle', 'eslint.config.js', '*.d.ts'],
  },
];
